### ISSUE TITLE
TypeScript compilation with --no-babel

### ISSUE THREAD

**Issue by styfle** [vercel/micro#12]
I am trying the `sleep.js` example with [TypeScript](https://github.com/Microsoft/TypeScript) and avoid Babel Transpilation since TypeScript performs Transpilation.

The output I get from TypeScript is the following:

``` js
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promise, generator) {
    return new Promise(function (resolve, reject) {
        generator = generator.call(thisArg, _arguments);
        function cast(value) { return value instanceof Promise && value.constructor === Promise ? value : new Promise(function (resolve) { resolve(value); }); }
        function onfulfill(value) { try { step("next", value); } catch (e) { reject(e); } }
        function onreject(value) { try { step("throw", value); } catch (e) { reject(e); } }
        function step(verb, value) {
            var result = generator[verb](value);
            result.done ? resolve(result.value) : cast(result.value).then(onfulfill, onreject);
        }
        step("next", void 0);
    });
};
var micro_1 = require('micro');
var then_sleep_1 = require('then-sleep');
exports.default = function (req, res) {
    return __awaiter(this, void 0, Promise, function* () {
        yield then_sleep_1.default(500);
        micro_1.send(res, 200, 'Ready!');
    });
};
```

It appears to start fine however visiting localhost:3000 has the following error

```
TypeError: then_sleep_1.default is not a function
```

I suspect this might require changes to `then-sleep` module however it would be nice to see how the same example without the async/await.

What is the expected ES6 code (without async/await) for this sleep example?

**Comment by rauchg** [comment]
Are you running it with the `--no-babel` flag?

**Comment by styfle** [comment]
@rauchg Correct I am running with `--no-babel` as the title says. I'm not entirely convinced that it is avoiding babel because startup time is still 1 or 2 seconds.

https://github.com/styfle/micro-ts-example/blob/master/package.json

**Comment by TooTallNate** [comment]
I believe the problem comes from the fact that all of the babel modules (except `babel-register`) [get imported unconditionally](https://github.com/zeit/micro/blob/03d83870fb43417f3e92ff6f6bf5bfcc0a346e09/bin/micro#L7-L12).

:+1: for fixing this because at the moment I'm not using `micro` CLI, partly because of this startup time issue.

**Comment by sergiodxa** [comment]
You can use `micro` without the CLI this way:

``` javascript
import micro from 'micro';

async function requestHandler(req, res) { ... }

micro(requestHandler).listen(process.env.PORT || 3000);
```

I don't know TS, but basically, the idea is that if you import `micro` you can use it to create a HTTP server passing your `requestHandler` (your function) as an argument and then using `.listen(port)`.

This way you can just run `node index.js`, of course, you should need to transpile your code from ES\* or TS to JS.

You can read about it in the [docs](https://github.com/zeit/micro#micro).

**Comment by styfle** [comment]
@sergiodxa I think this is really the correct solution. Thanks!
Here is the same thing in typescript:

``` ts
import * as micro from 'micro';
import {IncomingMessage, ServerResponse} from 'http';

async function requestHandler(req: IncomingMessage, res: ServerResponse) {
    res.writeHead(200);
    res.end('hello world');
}

micro(requestHandler).listen(process.env.PORT || 3000);
```

**Comment by rauchg** [comment]
Moving forward, we're making `micro-serve(1)` take the exported file that's been pre-compiled, which should be much better for production.
