### ISSUE TITLE
Default to port 3000 when providing empty -p

### ISSUE THREAD

**Issue by timneutkens** [vercel/micro#121]
Issue from #120

**Comment by leo** [comment]
Looks like [an issue](https://github.com/zeit/micro/blob/master/bin/micro#L22) in minimist...

**Comment by timneutkens** [comment]
https://github.com/substack/minimist/issues/98 seems like it's not supported out of the box.

**Comment by timneutkens** [comment]
@leo should we port to https://github.com/leo/args? 😏

**Comment by timneutkens** [comment]
Ah it's based on minimist, nvm then 😉

**Comment by timneutkens** [comment]
Documented in https://github.com/zeit/micro/pull/115
