### ISSUE TITLE
Start script without npm

### ISSUE THREAD

**Issue by JuanRamino** [vercel/micro#127]
Hi,

I want to start my app without npm but it doesn't work.

I have a code like this in index.js:
```
module.exports = async function (req, res) {
  ...
}
```
And starting it with npm works fine.

But if I try something like:
```
const srv = micro(async function (req, res) {
  ...
})
srv.listen(3000)
```
And starting it with `node index.js` I get an error: *Unexpected token function*

I'm using node v7.3.0.

Thanks

**Comment by albinekb** [comment]
if you use the `micro` bin then it will automagically apply [async-to-gen](https://github.com/leebyron/async-to-gen).

So you need to use that or start node with `node --harmony-async-await index.js`

**Comment by timneutkens** [comment]
You could also transpile it using `async-to-gen index.js > compiled.js` and then start it using `node compiled.js`.

**Comment by JuanRamino** [comment]
I use this solution:

```
npm install --save async-to-gen
```

And then I add in index.js

```
require('async-to-gen/register')
```

In this way I could start it with ```node index.js```

Thanks guys, good work!
