### ISSUE TITLE
AMQP and web support?

### ISSUE THREAD

**Issue by nfantone** [vercel/micro#13]
I know the motto says right there: _"Just HTTP!"_, but what if I wanted to use this same "micro"-approach and use AMQP as the transport layer? Could this be done without much hassle? Is there any _extension_ or plugin for this?

Also, if I'm tied to HTTP for transport: what's the benefit of using the framework compared to, say, plain `http` from Node, Express, Hapi, Koa, Restify and the like?

In fact, how does `micro` play along with web frameworks such as those? Is it possible to integrate them in some way? Could I, for instance, define API routes in Express and send messages over to another microservice?

**Comment by rauchg** [comment]
@nfantone 

The goal is to _avoid_ the pattern of multiple route definitions per service. Each microservice performs a single function.

In terms of why not native Node, the main reason is that it's not designed around `async` / `await`, and you'll probably roll out an ad-hoc solution like `micro` every time you want to use those. You'll create `Promise`-friendly versions of body parsing like `micro.json`, you'll do exception handling, etc.

You can certainly use this same technique for AMPQ:

``` js
export default async function ampqHandler () {
  /* … */
}
```

and then run it micro-style with your own tool: 

``` bash
$ ampq my-handler.js
```

As far as aggregating the micro-services into paths, I recommend NginX upstreams. That way `api.yourservice.com/woot` can forward traffic to the `woot` microservice, and many different paths can co-exist under the same host. This will benefit browser lookups, will unify SSL termination, etc.
