### ISSUE TITLE
Micro organization?

### ISSUE THREAD

**Issue by tomparkp** [vercel/micro#134]
I really like micro as an alternative to Koa - have you given any thought to creating something like a Micro JS community organization where people can host plugins etc?

**Comment by timneutkens** [comment]
That might conflict with https://github.com/micro. But it's an interesting idea 👍

**Comment by timneutkens** [comment]
cc @leo

**Comment by leo** [comment]
Why would people want to host plugins in a centralized place instead of being able to manage their own account completely and without restrictions?

**Comment by tomparkp** [comment]
I'd imagine for the same reason koa, Hapi, Express have them - to build a community around the framework. Given how minimal micro is though I'd understand if that isn't a goal of the project.

**Comment by leo** [comment]
Looks like someone is already doing that: https://github.com/zeit/micro/issues/134#issuecomment-275637858. 😄
