### ISSUE TITLE
Use random port if default one already in use

### ISSUE THREAD

**Issue by leo** [vercel/micro#139]
Just like we're doing it in `serve`, `micro` should use a random port if the current one is already in use (instead of just failing).

**Comment by timneutkens** [comment]
@leo only for development? I think this will introduce some issues when not hosting on `now` / require production deployments to always explicitly set port 3000.

**Comment by timneutkens** [comment]
I'm +1 for explicit port setting in production though 😉

**Comment by leo** [comment]
✔️
