### ISSUE TITLE
Creating an option to inform that you want to use micro using µWebSockets http wrapper, instead of node default http module.

### ISSUE THREAD

**Issue by arden** [vercel/micro#148]
Creating an option to inform that you want to use micro using µWebSockets http wrapper, instead of node default http module.

**Comment by timneutkens** [comment]
Can you elaborate more on this @arden? I'm not following what you're trying to explain 😅

**Comment by arden** [comment]
using µWebSockets http wrapper instead of node default http module.
https://github.com/uWebSockets/uWebSockets

**Comment by leo** [comment]
I don't see a reason for informing users about that in this package. They need to find it out by themselves...! 😄
