### ISSUE TITLE
Add helper for composing functions

### ISSUE THREAD

**Issue by onbjerg** [vercel/micro#156]
You can easily end up with code that looks like

```js
// Deply nested request handler
module.exports = foo(bar(baz(xyz(abc))))
```

And so on and so forth. Maybe we could include a function for easy function composition, so the above example would look like

```js
const { compose } = require('micro')

module.exports = compose(
  foo, bar, baz, xyz, abc
)
```

Also, with a compose function one might be able to do

```js
const { compose } = require('micro')

// Set up middleware
const middleware = [foo, bar, baz, xyz]

// Some checks that add more middleware by
// pushing them to the ``middleware`` array
if (process.env['xyz'] === 'foobar') {
  middleware.push(something)
}

module.exports = compose(...middleware, abc)
```

Usually I'll write the compose function myself for micro projects. I suppose the only reason we don't want to include it directly in micro core is if we want to be really slim.

Here's the compose function I usually write:

```js
const compose = (...fns) => fns.reduce((f, g) => (...args) => f(g(...args)))
```

**Comment by BorisChumichev** [comment]
I think it's better to keep API surface as small as possible. Utility libraries such as `ramda` or `lodash` usually have `compose` function, and It's very common to have them as a dependency in a project. Thus having `compose` in `micro` could be redundant.

**Comment by iamstarkov** [comment]
@onbjerg 

>     const compose = (...fns) => fns.reduce((f, g) => (...args) => f(g(...args)))

compose is supposed to take any number of functions, and only rightmost function is supposed to take any number of arguments, every other functions are unary. Correct implementation is like this

```js
// Takes functions
// separate right most function from rest functions
// Returns composed function which takes `arguments`
// Invokes each passed function after each other
// each function takes result of previous one
// but right most function can take any arguments
const compose = (...fns) => {
  const [tailFn, ...restFns] = fns.reverse();
  return (...args) => restFns.reduce(
    (value, fn) => fn(value),
    tailFn(...args)
  );
};
```

i would suggest to take a look into pipe or composeLeft:

```js
const pipe = (headFN, ...restFns) => (...args) => restFns.reduce(
  (value, fn) => fn(value),
  headFN(...args),
);

const compose = (...fns) => pipe(...fns.reverse());
```

**Comment by iamstarkov** [comment]
but anyway function composition is out of scope for micro and doesnt belong to this project

**Comment by iamstarkov** [comment]
@leo, @rauchg  i would suggest to close this issue
