### ISSUE TITLE
How to use micro with two routes?

### ISSUE THREAD

**Issue by rafaeljesus** [vercel/micro#16]
How would I design a service with more then one route?

For example I have a `event-trace-api` service where I trace all transactions in my app and expose a api where I can search for these events,

So basically I have 2 routes:
POST /v1/events
GET /v1/events/search

Following micro design I would have 2 separate servers, one for create and other for search, that looks too much for me,

Thanks

**Comment by sergiodxa** [comment]
I think you should use `search` as a query param instead of part of the url, then you can just check `request.query.search` and if it's undefined return the full list.

If you want to use `search` as part of the url then I'm sure you should to use 2 separate servers, one for the complete list and other one for the searched list.

**Comment by rafaeljesus** [comment]
Hi @sergiodxa thx for your reply,

That's not very intuitive to have one route to deal with POST and GET 

Looks like micro is a nano-service lib and that's totally fine I think

**Comment by sergiodxa** [comment]
Micro is just to create HTTP services using async/await and thinking in microservices, it's a wrapper for the `http` Node.js native module. But it not give you a router handler, you can use other router handlers which can receive the `request` object.

Thinking in how made that what about something like this?

``` javascript
import micro, {
  json,
  send,
  sendError,
} from 'micro';

/**
 * handle POST requests
 */
async function postHandler(request) { /* ... */ }
/**
 * handle GET requests
 */
async function getHandler(request) { /* ... */ }

/**
 * Check the request method and use postHandler or getHandler (or other method handlers)
 */
async function methodHandler(request, response) {
  try {
    switch (request.method) {
    case 'POST':
      return await postHandler(request);
    case 'GET':
      return await getHandler(request);
    default:
      send(response, 405, 'Invalid method');
      break;
    }
  } catch (error) {
    throw error;
  }
}

/**
 * our micro service, run methodHandler and send result as a response (or an error)
 */
const server = micro(async (request, response) => {
  try {
    send(response, 200, await methodHandler(request));
  } catch (error) {
    sendError(request, response, error);
  }
});

server.listen(process.env.PORT);
```

This way you have a function for each valid method.

**Comment by rafaeljesus** [comment]
@sergiodxa thank you very much for your explanation,

I thought doing this would go against micro principals design,

And this design totally fit into my `trace-events-api` service that I have running in production now,

Cheers

**Comment by rauchg** [comment]
@sergiodxa that's a beautiful example. Thank you for contributing it.

If you want routes, you can write another `micro` service that maps routes to backends, or use something like Nginx. You would host each of your services under a subdomain or port independently.

We're running 20+ microservices already in production. We had to use routing once, and we simply looked at `req.url` and performed a simple string comparison.

If you need a sophisticated routing mechanism, you're probably doing too much in one Node process. You'll pay in the form of more complicated debugging, conflated logging and lack of error isolation.

**Comment by rauchg** [comment]
Based on your example, in fact, I see that you want to do versioning. Not having routing built in is great for this.

Let's say `/v2/events/search` is the same, but `/v2/events` POST changed. You basically can bump versions by simply forwarding all `v2` traffic to the existing `v1` backends, and only add one exception, for `/v2/events` to go to `add-event-2.0.0.yourhost.com`. URLs are just labels!

**Comment by rafaeljesus** [comment]
Great explanation @rauchg 

I'll think on how to design this on Heroku, I don't have nginx right there,

So basically, are you doing in your production servers "one server for one route"?

Cheers

**Comment by rauchg** [comment]
Indeed. I have no experience with Heroku.

**Comment by rafaeljesus** [comment]
But hey I'm going to remove koajs form some microservices in production and use micro right now \o

**Comment by diorahman** [comment]
@sergiodxa I'm not sure we have `request.query` in micro's `request` object. Or I'm wrong?

**Comment by sergiodxa** [comment]
@diorahman yes, I just tried it and in the `request` object we don't have `request.query`, but it's possible to use [`url`](https://nodejs.org/api/url.html) and [`querystring`](https://nodejs.org/api/querystring.html) to get it in one line.

``` javascript
import qs from 'querystring';
import url from 'url';

async function requestHandler(request, response) {
  const query = qs.parse(url.parse(request.url).query);
  // do something
}
```

**Comment by onbjerg** [comment]
What about resources? E.g. the user with ID 1 would usually be `/users/1`. What would this look like in micro?

**Comment by sergiodxa** [comment]
I think you should do that yourself (I suppose with a RegEx), but I will quote @rauchg here:

> If you need a sophisticated routing mechanism, you're probably doing too much in one Node process. You'll pay in the form of more complicated debugging, conflated logging and lack of error isolation.

**Comment by rauchg** [comment]
A simple match utility would be nice for that. Not sure if it exists but:

``` js
const { id } = match('/users/:id', url);
```

would return `{}` for no match (eg: `'/user'`), `{ id: 1 }` for `/users/1` etc. Kind of saves you the trouble of checking that the regexp returns null, looking for the index of the capture group, etc.

**Comment by onbjerg** [comment]
@sergiodxa I don't think that quote applies here. I mean, you wouldn't want a micro service _just_ for getting single users, and then a microservice for getting a list of users, would you?

@rauchg Sure, I guess that'd work.

**Comment by TooTallNate** [comment]
@sergiodxa You can simplify your one-liner by adding `true` to url.parse():

``` js
const parsed = url.parse(request.url, true);
console.log(parsed.query);
```

**Comment by TooTallNate** [comment]
Related:
- https://github.com/gnoesiboe/route-match
- https://github.com/polmiro/url-match

**Comment by onbjerg** [comment]
Great resources, thanks @TooTallNate!

@rauchg Any plans on adding wiki pages with this content? I'm thinking of examples and/or resources. I think it would be beneficial. I think we already have some good ones, they just need a place to be put.

**Comment by rauchg** [comment]
@onbjerg that sound fantastic. It'd be cool to index the Wiki pages on the README for quick reference as well. PRs welcome

**Comment by onbjerg** [comment]
@rauchg Cool! You just need to enable the wiki first 👍

**Comment by onbjerg** [comment]
@rauchg Any updates on the wiki? 💃

**Comment by nblackburn** [comment]
@rauchg I went ahead and created a little utility based on your idea for matching urls.

https://github.com/nblackburn/micro-match

**Comment by domachine** [comment]
Just wanted you guys to know that I have worked a tiny router and architecture suggestions that work great with micro :) https://github.com/domachine/http-service-router

**Comment by diorahman** [comment]
When your intention is boilerplating, but it is ended up putting to much sugar https://github.com/diorahman/mcrsvc LOL!

**Comment by onbjerg** [comment]
@diorahman To be honest, routes shouldn't really be in a micro-service if possible. Limiting for HTTP method is alright.

**Comment by diorahman** [comment]
@onbjerg true, yeah. I'm still struggling on how to get the best workflow on building set of services, without sacrificing start time. I still think, when it comes to deployment, api gateway seems the best way (e.g. https://github.com/adobe-apiplatform/apigateway), but how about the development phase?

**Comment by just-boris** [comment]
For those, who are also looking for a routing solution I'd suggest looking at https://github.com/amio/awesome-micro

That repo contains interesting additions to the `micro` project, including several routing solutions.
