### ISSUE TITLE
Github Repo not in package.json

### ISSUE THREAD

**Issue by Floby** [vercel/micro#17]
I wanted to write how I liked your package but when displaying it on npmjs.org, there's no direct link to this repository =)

You could add this github repository to the package.json for people to be able to switch between npm and the github pages more easily.

**Comment by sergiodxa** [comment]
@Floby something like this https://github.com/zeithq/micro/pull/18?

**Comment by Floby** [comment]
Looks good to me =)

**Comment by rauchg** [comment]
Thanks @Floby and @sergiodxa for the patch
