### ISSUE TITLE
micro@7 "error Command failed with exit code 141."

### ISSUE THREAD

**Issue by johnlindquist** [vercel/micro#170]
A "hello world" app:
```
module.exports = () => `Hello`;
```

 with "micro": "^7.1.0" gives me a "error Command failed with exit code 141."

Reverting to 6.x.x works fine.

**Comment by timneutkens** [comment]
@johnlindquist which Node.js version and platform are you on? Just tried `v6.9.1` and `v7.6.0` on mac and had no issues 🤔

**Comment by johnlindquist** [comment]
Bash on Windows
Node v7.7.2

Hmm, it ran fine from a command prompt, but still fails from the bash prompt. I'm going to assume it's an issue with Bash on Windows. I'll refile over with them. Thanks.

**Comment by johnlindquist** [comment]
@timneutkens fyi, I commented out the "detect port" features and got it to work:

https://github.com/zeit/micro/blob/7.0.0/lib/index.js#L36

I'll do a bit more sleuthing, not sure if it's an issue with the `detect-port` lib or bash.

**Comment by johnlindquist** [comment]
So I've been hunting this down... I'm thinking it's from the `copy-paste` library:

Commenting out this one line fixes it:
https://github.com/zeit/micro/blob/master/lib/listening.js#L9

Here's the related issue on the `copy-paste` repo:
https://github.com/xavi-/node-copy-paste/issues/56

Bash on Windows uses Ubuntu... I'm trying to find someone to test on an ubuntu machine.

**Comment by timneutkens** [comment]
cc @leo same issue would be there on serve I guess 🤔 Just an FYI.

**Comment by calbertts** [comment]
I'm having this issue. Any update?

**Comment by johnlindquist** [comment]
@calbertts are you on Ubuntu?

**Comment by calbertts** [comment]
@johnlindquist No, I'm actually in MacOS, finally I had to downgrade Micro to v6.2.1, It seems an issue with the 7.x.x versions.
