### ISSUE TITLE
Exiting with 141 when Dockerized

### ISSUE THREAD

**Issue by stephenmathieson** [vercel/micro#191]
I've built a few services with `micro` but am unable to deploy them with Docker. I've setup an example at https://github.com/stephenmathieson/micro-docker-bug.

Am I missing something, or does Micro not support being run via Docker?

**Comment by timneutkens** [comment]
@floatdrop this is the copy issue right?

**Comment by timneutkens** [comment]
@stephenmathieson could you try it with the current master?

**Comment by stephenmathieson** [comment]
I've moved on for now -- just using Express. I'm kinda in a rush to get a prototype out.

I should be able to try again with `master` tomorrow-ish tho.

**Comment by timneutkens** [comment]
@stephenmathieson totally fine, no rush, I believe this was fixed on master 👍

**Comment by floatdrop** [comment]
@timneutkens yes, clipboardy from master works fine – https://github.com/stephenmathieson/micro-docker-bug/pull/1

**Comment by timneutkens** [comment]
Thanks @floatdrop much appreciated as always ❤️
