### ISSUE TITLE
Silent flag captures file

### ISSUE THREAD

**Issue by danreeves** [vercel/micro#196]
small DX issue

The current help text suggests you can `micro --silent server.js` but this will result in `args.silent = 'server.js'` and `file = undefined`.

I looked into `args` and found this issue https://github.com/leo/args/issues/27 was closed so not sure what your preferred solution would be.

<details>
<summary>Help text output</summary>

```
  Usage: micro [options] [command]

  Commands:

    help  Display help

  Options:

    -h, --help          Output usage information
    -H, --host [value]  Host to listen on (defaults to "0.0.0.0")
    -p, --port <n>      Port to listen on (defaults to 3000)
    -s, --silent        Silent mode
    -v, --version       Output the version number
```

**Comment by danreeves** [comment]
Thanks! 🏆

**Comment by leo** [comment]
Fixed in https://github.com/zeit/micro/releases/tag/7.2.0
