### ISSUE TITLE
invalid body

### ISSUE THREAD

**Issue by johhansantana** [vercel/micro#207]
Hello

I've never used micro before but when I try to use the example

```javascript
const {json} = require('micro')

module.exports = async function (req, res) {
  const data = await json(req)
  console.log(data)

  return 'Data logged to your console'
}
```

and make a post request it errors out saying `Invalid body`

**Comment by AutoSponge** [comment]
I think you'll need to share your POST code as well. I posed an example app using your code: https://glitch.com/edit/#!/giant-beam

**Comment by floatdrop** [comment]
@johhansantana make sure you are sending valid JSON body. This should do the trick:

```bash
curl -d "{}" localhost:3000
```

**Comment by leo** [comment]
Fixed in https://github.com/zeit/micro/pull/208

**Comment by kristojorg** [comment]
I am currently sending `curl -d "{}" localhost:3000` and getting back `Invalid Body` when trying to parse with `json`... any ideas?

**Comment by AutoSponge** [comment]
Make sure you're using `await json(req)`

**Comment by kristojorg** [comment]
It turned out I actually didn't need to be using `await json(req)`... when I omitted that I could access body just fine with `req.body` and objects in body as well.
