### ISSUE TITLE
Support for GET requests without a body

### ISSUE THREAD

**Issue by johnthethird** [vercel/micro#216]
I'm deploying `micro` services (and loving it!) into Kubernetes, which has a livenessProbe that does a GET with no body to check the health of the service, which causes `micro` to throw a 400 Invalid JSON error. 

So, this is how I implemented a health check by responding to a GET / with a 200. I am happy to submit a doc or example PR if this is the correct approach.

```js
'use strict'

import {send, json} from 'micro'
import jwtAuth from 'micro-jwt-auth'
import visualize from './visualize'

  // Import your custom command here
import cmd from './cmd'

const compose = (...fns) => fns.reduce((f, g) => (...args) => f(g(...args)))

// micro will error out with a 400 Invalid JSON if you GET /  Kubernetes has a livenessProbe
// that does just that, so return a 200 instead
const handleErrors = fn => async (req, res) => {
  try {
    return await fn(req, res)
  } catch (err) {
    if (req.method == 'GET' && req.url == '/' && err.statusCode == '400') {
      send(res, 200, '{"healthy": true}')
    } else {
      throw(err)
    }
  }
}

const handler = async(req, res) => {
  const input = await json(req)
  const output = await cmd(input)
  send(res, 200, output)
}

module.exports = compose(
  handleErrors,
  jwtAuth("sekret"),
  visualize
)(handler)
```

**Comment by jackzampolin** [comment]
I like this pattern. Can you show an example of how you have implemented `cmd`/`visualize`? Needless to say I would love to see this full example.

**Comment by johnthethird** [comment]
We packaged up the pattern here  https://github.com/KaleoSoftware/micro-hoofs

**Comment by samtgarson** [comment]
I'm not sure what your app does, but couldn't this also cover up a genuine 400 error produced from the main application? I'm guessing that `jwtAuth` could throw a code 400...

It might be safer to tell k8s to hit a specific endpoint (like `/ping` or whatever) then _proactively_ check if the request has that path and is a GET, and return the healthy response, before running the main application, that way there's no mix ups?

**Comment by leo** [comment]
Agreed with @samtgarson.

I also think that this definitely isn't something for core, as we need to can't stop throwing just for this one special case. I suggest taking a look at the package mentioned above and also writing it so that k8s hits a specific endpoint which has a special error handler! 😊
