### ISSUE TITLE
Serve static files from micro

### ISSUE THREAD

**Issue by fhelwanger** [vercel/micro#225]
Is there a way to serve static files from a micro instance? I was thinking about using `serve` and `micro` in the same server, but I couldn't find out how to do it.

#212 describes how to solve it using `nginx`, but I'm using `now`. Is there a way to do it without using two servers?

**Comment by dimapaloskin** [comment]
> #212 describes how to solve it using nginx, but I'm using now.

You can setup what you want (nginx in particular) inside docker container (`now` supports Dockerfile).
But I recommend using separate deploys and combine them through [path aliases](https://zeit.co/docs/features/path-aliases)

**Comment by leo** [comment]
`serve` should export the middleware!

**Comment by fhelwanger** [comment]
@dimapaloskin Interesting solution using `path aliases`, thanks for that 👍 

But in my case, it's a really tiny web server which I'd like to combine both `serve` and `micro` without worring about configuring docker and, if possible, maintain both in a single server.

**Comment by fhelwanger** [comment]
@leo Yeah, I was thinking about something like that.

**Comment by leo** [comment]
I'm happy to accept a PR for that! The import should look like this:

```
const {server, middleware} = require('serve')
```

`server` already exists. Or do you have a better idea for the naming?

**Comment by fhelwanger** [comment]
Sounds good to me.

I'll try to work on it later this week 😉

**Comment by leo** [comment]
Wonderful!

**Comment by leo** [comment]
This discussion/PR should continue here: https://github.com/zeit/serve

**Comment by Kikobeats** [comment]
any way to combine serve +  micro?
