### ISSUE TITLE
Micro is not very "lightweight"

### ISSUE THREAD

**Issue by styfle** [vercel/micro#234]
In the readme it says "micro" and "lightweight", but doesn't say what the installed size is. So I went ahead and did my own tests.

```sh
mkdir micro-example
cd micro-example
npm init -y
npm install --save micro
du -sh node_modules
```

This shows **9.2M** for `micro@7.3.2` and all it's dependencies.

Now lets try with the popular express framework.

```sh
mkdir express-example
cd express-example
npm init -y
npm install --save express
du -sh node_modules
```

This shows **1.8M** for `express@4.15.2` and all it's dependencies.

I also repeated the same steps for `koa@2.2.0` (**2M**) and `hapi@16.1.1` (**1.3M**) which are also popular web frameworks.

That means micro is the largest of the frameworks one might use to make microservices.

Is this expected?

**Comment by leo** [comment]
`micro` is not just a framework, but also comes with a development CLI (express and koa don't, I don't know hapi). But yes, we're already working on splitting it out!

**Comment by styfle** [comment]
> we're already working on splitting it out!

Splitting what out?

**Comment by leo** [comment]
The development CLI... 😄

**Comment by albinekb** [comment]
The code running is a lot less than express / koa, who cares about installed space in 2017?

**Comment by leo** [comment]
@albinekb Yea, that's my opinion. But sadly, a bigger package also means longer installation times in production (which makes deployments slow).

**Comment by styfle** [comment]
@albinekb My assumption is that `micro` was designed for implementing microservices.

If you add `micro` as a dependency to a 1000MB mono-repo, then it's only a 1% increase.

If you add `micro` as a dependency to 500 individual microservices, that's a 5000MB (5GB) increase in size.

**Comment by austinfrey** [comment]
I'm getting 17mb now. @leo what's the status of splitting out the cli?

**Comment by timneutkens** [comment]
@aafrey https://github.com/zeit/micro/pull/260

**Comment by austinfrey** [comment]
@timneutkens thanks! what are you using to measure package size? the printout looks really nice!

**Comment by timneutkens** [comment]
@aafrey this one https://github.com/siddharthkp/cost-of-modules

**Comment by austinfrey** [comment]
thanks!

**Comment by leo** [comment]
Very close!

**Comment by tim-phillips** [comment]
The split happened: 

https://zeit.co/blog/micro-8

**Comment by styfle** [comment]
I just checked v9.0.0 and it reports **747K**.
That's significantly smaller now and appears to be the smallest of the 4 (express, koa, hapi, micro).

Great job! 🎉 

---
*Update 2018*: You can visualize the install size difference between [micro@7.3.3](https://packagephobia.now.sh/result?p=micro@7.3.3) and [micro@8.0.0](https://packagephobia.now.sh/result?p=micro@8.0.0) with my new tool, [Package Phobia](https://github.com/styfle/packagephobia), which is much easier than installing yourself 😄
