### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by AutoSponge** [vercel/micro#235]
I will soon have `micro` in production. I know my containers have 4 cores but micro only uses one(1). I know zeit loves the 0-config and no-api api but what would you accept as a PR for supporting [clusters](https://nodejs.org/api/cluster.html)? 

I've looked at the `micro-cluster` repo, and I don't think it's what I want. First, `http-proxy` is not a load balancer but cluster has predictable behavior and uses IPC to make sure child processes are running before marking them in (say for round-robin). Second, I would prefer the cluster grow to the size of its container rather than having to configure it.

I believe the performance gains could be substantial for a service under heavy load.

Ideas to control behavior (not mutually exclusive):

- [ ] 0-config
  - always 1 core in `development` env 
  - always 50% cores in `production` env
  - always max cores in `performance` env
  - PRO: familiar, simple
  - CON: may hide behavior for non-thread-safe operations until in a prod/perf env
- [ ] cli flag
  - default 1 core
  - override behavior with flags (`--cores, --sched`)
  - PRO: extensible, opt-in
  - CON: requires editing deploy/run scripts
- [ ] dot-file (`.micro`?)/package.json prop
  - default 1 core
  - override cluster behavior with config (`cores`: % or #, `sched`: round-robin or none, etc.)
  - PRO: extensible, opt-in, if running under watch, service will auto-restart on change
  - CON: requires changing config file to change behavior
- [ ] runtime api
  - default 1 core
  - override behavior with call to api
  - PRO: allows changing behavior without restarting, allows for container manager integration
  - CON: api calls need to be secure and not interfere with app calls

Additional features:
- [ ] rolling replacement - after a `/src` file changes, the worker pool cycles each thread one-at-a-time until the service is refreshed. Leads to 0 dropped requests.

Decisions to make:
- is micro the controller and app code is the worker? OR is micro cloned in each thread?

**Comment by iamstarkov** [comment]
hi @AutoSponge, have you seen [micro-cluster](https://github.com/zeit/micro-cluster)?

**Comment by AutoSponge** [comment]
@iamstarkov yes, my comments are in the second paragraph.

**Comment by floatdrop** [comment]
@AutoSponge I believe scaling should be done by the cloud provider, not by micro itself. Did you look at [pm2](http://pm2.keymetrics.io) for clustering micro app?

**Comment by AutoSponge** [comment]
@floatdrop I agree horizontal container scaling should be handled by the cloud provider. My provider gives me containers with 4 cores. Unless I'm doing file reads, node.js will never use more than 1. So, I'm wasting capability that I'm paying for. However, if I have a thread-safe app, I can use node's cluster module to multithread the app and utilize the containers resources.

I'll look at pm2.

EDIT: pm2 uses a GNU-AGPL license. My organization is reviewing it but may not approve it. In that case, I'd need to write my own clustering capability or find another alternative.

**Comment by AutoSponge** [comment]
I rewrote `test-listen` for clustering as a precursor to wrapping micro. The reference to `test-listen`just requires my server and invokes `listen`. I'd like a better way to do that if possible. Any thoughts?

```js
const cluster = require('cluster')
const cpus = require('os').cpus().length
const debug = require('debug')('cluster')
const path = require('path')
debug(`master process started on ${process.pid}`)
const workersCount = parseInt(process.argv[2]) || cpus
let createWorkers = workersCount

cluster.setupMaster({
  exec: path.join(__dirname, 'test-listen'),
  silent: false
})
cluster.on('exit', (worker, code, signal) => {
  if (worker.exitedAfterDisconnect === true) {
    debug('voluntary shudown')
  }
})
cluster.on('message', (worker, message) => {
  debug({ worker: worker.id, message })
})
const port = new Promise(resolve => {
  cluster.once('listening', (worker, { port }) => {
    const address = `http://localhost:${port}/`
    debug(`cluster of ${workersCount} workers started at ${address}`)
    resolve(address)
  })
})

while (createWorkers--) {
  cluster.fork()
}

module.exports = () => port
```

**Comment by leo** [comment]
Thank you for the effort you've put into creating this issue. I understand that micro-cluster might not be fully suitable for you yet, but I definitely think that we should move the discussion to [here](https://github.com/zeit/micro-cluster) and then consider improving it. This definitely won't be a core feature, as we want to keep it as slim and light as possible (huge rewrite coming). 😊
