### ISSUE TITLE
Docker Support? 

### ISSUE THREAD

**Issue by rturk** [vercel/micro#236]
How can I Run this inside a docker?

**Comment by sergiodxa** [comment]
Something like this:
```
FROM node:argon
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install
COPY . /usr/src/app
EXPOSE 3000
CMD [ "npm", "start" ]
```
_Copied from and old version of the documentation_. It's just installing node inside the container, running your microservice and exposing the used port.

**Comment by braytonstafford** [comment]
Here is the Dockerfile and package.json I'm using for my service using micro.  Use `npm start` to start it up which will be the default command that is run when the container starts. If the service throws an error the docker container will exit.

```
{
  "name": "yourService",
  "version": "0.0.1",
  "description": "The greatest service in the world",
  "main": "index.js",
  "scripts": {
    "test": "ava \"**/*.test.js\" --verbose",
    "watch:test": "npm t -- --watch",
    "lint": "eslint .",
    "start": "micro -p 20001"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/your_repo/your_service.git"
  },
  "author": "You",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/your_repo/your_service/issues"
  },
  "homepage": "https://github.com/your_repo/your_service#readme",
  "dependencies": {
    "jsonschema": "^1.1.1",
    "micro": "^7.0.6",
    "mysql": "^2.13.0"
  },
  "devDependencies": {
    "ava": "^0.17.0",
    "eslint": "^3.16.1",
    "eslint-config-google": "^0.7.1"
  }
}
```

```
# Use Node v7 as the base image.
FROM node:7

# File Author / Maintainer
MAINTAINER Brayton Stafford

# Provides cached layer for node_modules
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /app && cp -a /tmp/node_modules /app/

# Define working directory
WORKDIR /app
\# Add everything in the current directory to our image, in the 'app' folder.
ADD . /app

# Expose our server port.
EXPOSE 20001

# Run our app.
CMD ["npm", "start"]
```

**Comment by rturk** [comment]
tks, closing this

**Comment by jnoleau** [comment]
You should not use "npm xxx" in a Dockerfile. This will result with npm as the process with PID 1 and your node exec with PID > 1 : 
* the docker stop will be quiet long
* your node process will never receive the SIGTERM event to do a gracefull stop

Instead use `CMD ["npx", "micro", ..]` or something like `CMD ["/app/node_modules/micro", ..]` to have the good behaviour (`micro: Gracefully shutting down. Please wait...` when you stop the container)

**Comment by lysandroc** [comment]
Thanks, that's helped me a lot.
