### ISSUE TITLE
Example usage with AWS Lambda?

### ISSUE THREAD

**Issue by subodhpareek18** [vercel/micro#239]
It seems like Micro is a really good fit with AWS Lambda, given it's all about writing functions as single purpose services.

Could there be a documented example of micro's usage with AWS Lambda. There are already two popular libraries that enables us to work with AWS Lambda, so a vanilla example along with an example each with the following libs would be incredibly helpful.

https://www.github.com/serverless/serverless
https://github.com/apex/apex

**Comment by kandros** [comment]
I do not think they will play well together, micro creates an HTTP server that listens for requests, while an AWS lambdas are stateless function that cannot run for more than 5 minutes.

**Comment by leo** [comment]
Correct. We're most likely not going to an add example for this... 😊
