### ISSUE TITLE
Question: How do I initialize data before starting the server

### ISSUE THREAD

**Issue by serle** [vercel/micro#250]
I'm trying to read some option variables into the application in such a way that they are available to the service function when it is first called. How would I be able to do this in micro?

**Comment by floatdrop** [comment]
@serle you can read them and return in promise like so:

```js
const dataProvider = new Promise((resolve) => resolve(42));

module.exports = async (req, res) => {
    let data = await dataProvider;
    return data;
}
```

Until data is available all requests will wait for promise to resolve.

**Comment by serle** [comment]
@floatdrop thanks, great. I can achieve what I need for now. 

I was thinking that maybe micro could make this use case clear by adding an initialization hook `async (args) => {}` and a termination hook `async(props) => {}` where arg are command line arguments and props are the props created during the initialization hook. Then add props to the req/res hook as a final optional parameter. That way it has the ability to do service startup and shutdown stuff cleanly.

**Comment by dimapaloskin** [comment]
Also you can create server manually.

`index.js`
```js

const micro = require('micro');
const sleep = require('async-sleep');

const server = micro(async (req, res) => {
  return 'Hi :)';
});

console.log('Waiting...');
sleep(5000)
  .then(() => {
    console.log('Run server');
    server.listen(3000);
  })

```

Run:
```bash
node index.js
```

**Comment by serle** [comment]
I agree that we can do all this, but making a clean API with a set of standard hooks means that we don't have to "open the black box", which to me defeats the purpose of micro. In this case we might as well just go back to express. To me a set of lifecycle hooks with a baked in compose component, to setup middleware, would provide a more feature rich experience.
