### ISSUE TITLE
Prevent clipboard copying

### ISSUE THREAD

**Issue by olivierlesnicki** [vercel/micro#255]
When using micro with nodemon (for live-reload) the `copying` feature can become frustrating. Every time the server is restarted the URL is copied in the clipboard.

micro should support a way to pass a `-noclipboard` option, disabling the automatic copy feature when doing local development.

**Comment by leo** [comment]
What about `--silent`? This already exists.

**Comment by olivierlesnicki** [comment]
Tried using `--silent` it doesn't work...

**Comment by leo** [comment]
This feature will be moved out as the next step. 😊
