### ISSUE TITLE
how to add headers to the response?

### ISSUE THREAD

**Issue by luisrudge** [vercel/micro#26]
I need to support cors

**Comment by luisrudge** [comment]
Sorry, I totally missed micro-core: https://github.com/zeit/micro-core/blob/c59c7a6d1d4a09fd55d5ba533cd3a2f3e685fcff/lib/index.js#L61

**Comment by tim-phillips** [comment]
`res` is a node response object:

```javascript
res.setHeader('Access-Control-Allow-Origin', '*')
```

https://nodejs.org/api/http.html#http_response_setheader_name_value
