### ISSUE TITLE
Trailing comma error

### ISSUE THREAD

**Issue by elrumordelaluz** [vercel/micro#262]
👍 First of all, first time using `micro` and seems pretty easy to use allowing fast workflows.

☝️The point is that I am using [prettier](https://github.com/prettier/prettier) with the option `trailingComma: all`. Then, when I have a methods like this: 

```
const sampleNotification = gateway.webhookTesting.sampleNotification(
  braintree.WebhookNotification.Kind.SubscriptionCanceled,
  'myId',
)
```
it complains with an
```
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
```

Removing the _trailing comma_ pass without the `Error`

**Comment by leo** [comment]
I don't think a trailing comma should sit there, only in objects...

**Comment by elrumordelaluz** [comment]
Yep, supposed the same, probably a `prettier` issue…

**Comment by elrumordelaluz** [comment]
[related](https://github.com/prettier/prettier/issues/1398#issuecomment-296736717)
