### ISSUE TITLE
Custom timeout support?

### ISSUE THREAD

**Issue by DLesage25** [vercel/micro#267]
Can you add support for specifying a microservice's timeout?

**Comment by floatdrop** [comment]
@DLesage25 what do you mean by `microservice timeout`? Usually client library should support timeouts, not serverside. But you can do it on server side:

```js
pTimeout = require('p-timeout');

module.exports = async () => {
    try {
        send(await pTimeout(someAsyncStuff, 1000));
    } catch (err) {
        if (err instanceof pTimeout.TimeoutError) {
            return send('Something does not responded', 500);
        }
        throw err;
    }
}
```

**Comment by leo** [comment]
`await sleep()` 😴 

https://www.npmjs.com/package/ko-sleep
