### ISSUE TITLE
Webpack packages cannot be supported？

### ISSUE THREAD

**Issue by wjszxli** [vercel/micro#271]
I want to use webpack to package my code file, but I'm reporting such a mistake. Can't I support the webpack packaging file?

`micro: "/Users/wangjunsheng/learn/micro/build/bundle.js" does not export a function.
error Command failed with exit code 1.
error Command failed with exit code 1.`

**Comment by sergiodxa** [comment]
Yes, but you need to configure webpack to export a module, that way it will export a function, you can also use micro API to run micro instead of the CLI.

**Comment by iamstarkov** [comment]
@wjszxli why do you need a webpack package to run in micro?

**Comment by leo** [comment]
This is not a micro issue. Please configure your webpack instance so that the bundle exports a function that micro can run.
