### ISSUE TITLE
Micro service does not working locally on some machines.

### ISSUE THREAD

**Issue by kmigntw** [vercel/micro#272]
Hi there, 
I start using micro library. 
I install it with npm install micro --save and I get the latest version. I was following the  [tutorial](https://www.npmjs.com/package/micro)
My package.json is with 
```
{
  "name": "ais-micro-packman-projectlist",
  "scripts": {
    "start": "micro"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "lodash": "latest",
    "micro": "latest"
  }
}
```

the files and folders that I have are 
<img width="207" alt="screen shot 2017-06-21 at 12 30 44" src="https://user-images.githubusercontent.com/15684891/27380002-ce05656e-567d-11e7-9b57-b6fa2d5b88a7.png">

The code that I have in index.js is a simple axios post...

When I start the project I get 
<img width="1647" alt="screen shot 2017-06-21 at 12 13 21" src="https://user-images.githubusercontent.com/15684891/27380039-fd8b5276-567d-11e7-8477-7748f76499a0.png">

I send the project to my colleague and when he tried it everything went well
<img width="1000" alt="screen shot 2017-06-21 at 12 02 50" src="https://user-images.githubusercontent.com/15684891/27380079-1b3ad95e-567e-11e7-8a4f-01557aeb26c6.png">

I start new project... I get the same error. Restart the machine tried from the scratch - same error...
tried with the old one - same error

I'm really curious why is this happening? The code and everything is absolutely the same. We both use Mac OS.

**Comment by dscx** [comment]
@kmigntw Can you post other global dependency versions? Node and NPM specifically. (or just compare with your colleague).

**Comment by kmigntw** [comment]
Hi, thank you for your reply. The problem was that I was using an internal network with some restrictions and my colleague was on a public one. The server that I was trying to connect has some restrictions and that's why I had this problem. I close it yesterday when I found the problem but I don't know how to delete it. Thanks anyway :)
