### ISSUE TITLE
No feedback on wrong content-type

### ISSUE THREAD

**Issue by augustovictor** [vercel/micro#273]
I struggled for a whole day before finding the solution. 

My scenario is a `vue` application sending post requests to a `micro` app. However the `content-type` in `axios` header in `vue` was set as `application/json` which was not what `micro` was expecting. But there was no feedback on it. The request was just timing out.

**Comment by leo** [comment]
You should check for the content type by yourself on the API and throw back an error if your service can't handle it. Since the list of content types will be extended with time, I don't think it makes sense to hard code it. I hope you can understand that! 😊
