### ISSUE TITLE
Error: Invalid JSON

### ISSUE THREAD

**Issue by johhansantana** [vercel/micro#276]
Hello

I'm trying to send a json formatted object to a micro service I'm trying to create but the console logs `Error: Invalid JSON`

What I'm sending is this
```javascript
{
  "email": "test@email.com",
  "fullName": "Name",
  "phone": "7877877878",
  "address": "addresssss",
  "town": "town",
  "zipCode": "00777"
}
```

and my micro is this:
```javascript
const {buffer, text, json} = require('micro');

module.exports = async (req, res) => {
  const js = await json(req);
  console.log('js: ', js);
  return 'successss'
};
```

when I do `curl -d "{}" localhost:3001` it works though.

*edit*
Just in case this is what I'm using to make the `post`
```javascript
  submit() {
    const { form } = this.props;
    axios.post('http://localhost:3001', form.contactForm.values).then(res => {
      console.log('success: ', res);
    }).catch(err => {
      console.error('Error: ', err);
    });
  }
```

**Comment by timneutkens** [comment]
Issue here was the preflight request which also triggered the json parse. Helped Johhan in slack.

**Comment by johhansantana** [comment]
@timneutkens yes, using https://github.com/possibilities/micro-cors fixed this. Thanks!

**Comment by colkito** [comment]
I'm using [micro-cors](https://github.com/possibilities/micro-cors), but request still failing (Error: Invalid JSON) from a jQuery request.
From curl its fine. 🤔

**Comment by donedgardo** [comment]
I'm having the same issue, using postman to make the request. Invalid json output. `text` works though

**Comment by LanmeijingLucky** [comment]
do as this: 

```
curl -d  '{"name":11}' localhost:5600/lampcreate
```

must the single quotation marks (' ') include double quotation marks (" "), like above.

**Comment by 0xpatrickdev** [comment]
I am having a similar issue, but wasn't able to solve it after reading through this thread and looking at `micro-cors`.

My code looks like this:

```js
const { send, json } = require('micro')
const Nightmare = require('nightmare')

module.exports = async function (req, res) {
  const data = await json(req)
  console.log("DATA", data)

  const nightmare = new Nightmare({show: true})

  const link = await nightmare
    .goto('https://duckduckgo.com')
    .type('#search_form_input_homepage', data.query)
    .click('#search_button_homepage')
    .wait('#r1-0 a.result__a')
    .evaluate(() => document.querySelector('#r1-0 a.result__a').href)
    .end()
    .then((url) => {
      console.log("success")
      return send(res, 200, {url: url, error: false})
    })
    .catch((error) => {
      console.log("error")
      return send(res, 200, {url: null, error: error})
    })
}
```

```json
{
  "scripts": {
    "start": "micro",
    "dev": "micro-dev"
  },
  "dependencies": {
    "micro": "^9.0.1",
    "micro-cors": "^0.0.4",
    "nightmare": "^2.10.0"
  },
  "devDependencies": {
    "micro-dev": "^1.4.0"
  }
}
```

It works as expected with `micro-dev`, posting `curl -d '{"query": "github nightmare"}' http://localhost:300` returns `{"url":"https://github.com/n1ghtmare","error":false}`

But in production, I get `An error occured with your deployment` as a response and `Error: Invalid JSON` in the server logs.

**Comment by nirnaor** [comment]
Adding micro-cors and following [these instructions](https://github.com/possibilities/micro-cors) solved the problem for me. Perhaps it should be added in the docs as well.
