### ISSUE TITLE
Simple, could be simpler :)

### ISSUE THREAD

**Issue by beders** [vercel/micro#279]
I think you are going the right direction with `micro`, but as a user, I still have to check when to use `async` and when to use `await`.

Consider this:
```
const {buffer, text, json} = require('micro')
module.exports = async (req, res) => {
  const buf = await buffer(req)
  console.log(buf)
  // <Buffer 7b 22 70 72 69 63 65 22 3a 20 39 2e 39 39 7d>
  const txt = await text(req)
  // '{"price": 9.99}'
  const js = await json(req)
  // { price: 9.99 }
  console.log(js.price)
  return '''
}
```

Now consider this:
```
module.exports = (req, res) => {
  const buf = buffer(req)
  console.log(buf)
  // <Buffer 7b 22 70 72 69 63 65 22 3a 20 39 2e 39 39 7d>
  const txt = text(req)
  // '{"price": 9.99}'
  const js = json(req)
  // { price: 9.99 }
  console.log(js.price)
  return '''
}
```

That is simpler, less code and takes the guess-work out of which functions are already using `await` internally and which don't, the default being 'sane', i.e. functions return useful values and not promises.

**Comment by j-f1** [comment]
The problem is that your second example will lock up the Node process until the request finishes uploading; while the first one will allow many requests to happen in parallel. This is because the `await` syntax exits the function until the promise resolves, allowing other code to run in the interim.

**Comment by leo** [comment]
You don't need to use `await` or `async` when using synchronous functions. This is a matter of language design and has nothing to do with micro 😊

**Comment by beders** [comment]
I wasn't very clear: I'm advocating for `buffer`, `text`, `json` using `await` *internally*, so your users don't have to!
There will no locking as fundamentally everything runs asynchronously, but the users of your API can use it without having to actually care.

**Comment by j-f1** [comment]
There is no way to use `await` internally and expose a synchronous API. If a function uses `await`, it must be an `async function`, which means that the user must call it with `await` if they want a non-`Promise` value back. 

`await` isn’t magic, it’s just syntactic sugar.

**Comment by beders** [comment]
Ouch. Yeah, reading the spec helps. async/await is really just sugar. No transformation into state machines like ClojureScript's async. My bad and sorry for the interruption.
