### ISSUE TITLE
Overwrite of clipboard with nodemon

### ISSUE THREAD

**Issue by vintagexav** [vercel/micro#282]
This is the best way to develop micro services, however when you use nodemon, it restarts the server as expected, but it also write the localhost address in the clipboard. It is problematic to lose your clipboard everytime you save a file. Could we do something about that? Requiring micro, we should be allowed to pass a boolean to disable the auto overwrite of the clipboard.

**Comment by vintagexav** [comment]
Something like clipless of zeit/serve: https://github.com/zeit/serve/issues/248

**Comment by leo** [comment]
We're going to move this feature out. In turn, I'm closing this issue... 😊
