### ISSUE TITLE
Hot Reloading 🔥

### ISSUE THREAD

**Issue by tim-phillips** [vercel/micro#285]
Is it possible for micro to reload on save? Has this been discussed anywhere? It would greatly help the development experience.

**Comment by leo** [comment]
We‘re currently working on a separate package that will be able to handle this. Keep your eyes on the releases page! ☺️

**Comment by tim-phillips** [comment]
Thanks @leo! You guys are on it. 

https://github.com/zeit/micro-dev

Hot Reloading
Logs
Automatic Port Selection
Clipboard Support
