### ISSUE TITLE
server.close([callback]) much older than v6

### ISSUE THREAD

**Issue by randallsquared** [vercel/micro#287]
@leo    Just noticed the workaround for `server.close` accepting no callback... I'm not sure what gave you that impression, but that callback has been present at least since 0.10:

https://nodejs.org/docs/latest-v0.10.x/api/http.html#http_server_close_callback

Opening a new issue for this probably isn't the best way to mention it, but comments seem to be closed to us non-contributors.  :|

**Comment by leo** [comment]
Maybe it didn‘t work before? At least it doesn‘t work on Node.js 6...

**Comment by randallsquared** [comment]
Well, I'm not sure why that would be.  `server.close` has some surprising behavior around keep-alives, but that doesn't seem to have changed for 8.x.   In any case, I'll close this and get out of your hair.
