### ISSUE TITLE
Unhandled rejection Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by thelinuxlich** [vercel/micro#289]
I'm getting this error sometimes, what can possibly be happening?

**Comment by littleStudent** [comment]
I think you are trying to set the headers after micro already sent the response.

You are calling `send()` before setting headers?

**Comment by thelinuxlich** [comment]
I discovered what's going on: I thought send() would end the response and return from all logic but actually I have to return manually. This is a pain point with micro(and vanilla node.js), because if I have many places with send() in the same route but different modules I have to check res.headersSent a lot

**Comment by leo** [comment]
`send()` DOES end the response. There's no way `send()` would be able to "return from all logic" by itself, looking at how JavaScript is designed. You would have to do this:

```js
send(...)
return
```

**Comment by thelinuxlich** [comment]
but you agree with what I have to do? Check res.headersSent before every module executing in the request?

**Comment by leo** [comment]
No, I don't get that part. Reading from top to bottom, you can expect everything BEFORE `send()`, including everything AFTER `send()` (if you don't use `return`) to be executed. So if you want something to be executed after the response was sent, place it after `send()` and if there's something that is required to generate the response, you need to place it before `send()`... 🙈 

No need to check if the headers were sent already.

- After `send()`, they're always marked as sent
- Before `send()`, they're never marked as sent

**Comment by thelinuxlich** [comment]
It will be easier with a example:

```javascript
module.exports = (req, res) => {
  await authorization(req,res); // inside authorization there are some validations that can return send(403)
  if(!res.headersSent) {
    await bootstrapSession(req, res); // again, more validations that can return send(403)
    if(!res.headersSent) {
         await routeLogic(req, res); // again, more validations that can return send(403)
         if(!res.headersSent) {
              render(req, res); // will do some stuff and return send(200)
         }
    }
  }
}
```

**Comment by leo** [comment]
I suggest making each of these methods return a value based on which you can then decide if you want to `return` or not. Like:

```js
const authNeeded = await authorization(req,res)

if (authNeeded) {
  return
}
```

**Comment by thelinuxlich** [comment]
you are totally right :)
