### ISSUE TITLE
Avoid "Error: Can't set headers after they are sent"

### ISSUE THREAD

**Issue by amio** [vercel/micro#292]
The original talk https://github.com/zeit/micro/pull/286#pullrequestreview-53121000

Currently in this case:

```javascript
const { send } = require('micro')
module.exports = async (req, res) => {
    send(res, 200, 'OK')  // in some where
    return 'Another OK'  // somehow
}
```

micro will try to send "Another OK" as response but encounter "Error: Can't set headers after they are sent".

We might need to check if response was sent before dealing with return value from handler.

Also this check may better fits in `micro-dev`. Any idea is welcome 😃

**Comment by leo** [comment]
Very good idea! Can you please move this to [micro-dev](https://github.com/zeit/micro-dev)? I don't think we need the overhead in production if the issue can be fixed in development.
