### ISSUE TITLE
Micro swallows error

### ISSUE THREAD

**Issue by markmarijnissen** [vercel/micro#294]
I had a sytax error in my file, but all I got was:

```
micro: In order for `async` & `await` to work, you need to use at least Node.js 8!
micro: https://err.sh/micro/old-node-version
```

because of this line: https://github.com/zeit/micro/blob/master/lib/handler.js#L29

It was a good guess, but misleading and hard to debug.

(I'm aware of micro-dev, but I don't need all the devtools)

**Comment by runegame** [comment]
install Node V8 and run...

**Comment by leo** [comment]
Oh, right - it only happens if your Node.js version doesn't support async and await.

**Comment by TooTallNate** [comment]
I think @markmarijnissen is saying that he received the async/await message as a false-negative. The _actual_ problem was a JS syntax error in his code and then he got the misleading error message.

**Comment by TooTallNate** [comment]
To wit:

```
$ node -v
v6.10.3

$ cat server.js
module.exports = async (req, res) => {
  (1+
}

$ micro server.js
micro: In order for `async` & `await` to work, you need to use at least Node.js 8!
micro: https://err.sh/micro/old-node-version
```

**Comment by leo** [comment]
Yes, but the error is will only get triggered if: A syntax error occured PLUS your Node.js version doens't support async/await. So if after doing what the error says (upgrading) you see the actual error. Isn't that what we want? Or should we allow people to write APIs without async/await? I mean, it's possible...

**Comment by TooTallNate** [comment]
OP wasn't originally using `async` though. Sorry, my first example was bad since it used async.

For example:

```
$ node -v
v6.10.3

$ cat server.js
module.exports = function (req, res) {
  return (1+
}

$ micro server.js
micro: In order for `async` & `await` to work, you need to use at least Node.js 8!
micro: https://err.sh/micro/old-node-version
```

**Comment by markmarijnissen** [comment]
Yes, errors show never be misleading. If I want to use micro without async /await, it should be possible. 

Also, if I use a async-to-gen, I do have support, but still the misleading error would be triggered. (your async detection cannot detect async to Gen in all cases)

**Comment by markmarijnissen** [comment]
My use case is aws lambda, which is still stuck at 6. 10.
