### ISSUE TITLE
set Content-Type to 'text/plain' when a string is being sent?

### ISSUE THREAD

**Issue by andyburke** [vercel/micro#296]
If I'm reading code correctly, can't we assume if we get to here:

https://github.com/zeit/micro/blob/master/lib/index.js#L75

... that the Content-Type should be 'text/plain'?

Willing to fork/implement, but this is my first dive into micro and I'd like some feedback before undertaking the work. Is my understanding correct or am I missing something?

Thanks!

**Comment by floatdrop** [comment]
It could break some code, because without `Content-Type` header browsers guess about content of response and almost always it will be `text/html`, but `text/plain` will override it and browser will show text page instead of HTML.

**Comment by andyburke** [comment]
Indeed. It looks like Content-Type should be left unset if the content isn't known: https://tools.ietf.org/html/rfc7231#page-11

Closing, thanks.
