### ISSUE TITLE
How to I use micro with pkg?

### ISSUE THREAD

**Issue by otissv** [vercel/micro#300]
I'm trying the 'Welcome to Micro' example and trying to build with pkg but it immediately exits with pkg. micro dev is working ok. I pkg supported?

**Comment by sergiodxa** [comment]
You need to create an entry file for pkg where you run micro programmatically.

**Comment by timneutkens** [comment]
As far as I know @igorklopov demo'ed the case of pkging a micro app. It was using the `require('micro')' was though, not the cli :+1:

**Comment by otissv** [comment]
Thanks, it's working.  used the **Programming Use** from the README.md, which uses `require('micro')`

**Comment by timneutkens** [comment]
👌
