### ISSUE TITLE
Shouldn't micro automatically set the charset of the response to UTF-8?

### ISSUE THREAD

**Issue by thelinuxlich** [vercel/micro#301]

**Comment by albinekb** [comment]
I think so too, is there any reason **not** to do it? 🤔

**Comment by floatdrop** [comment]
I would not recommend to do this in general for all responses, but `application/json` can be postfixed with `utf-8` encoding safely. There are [some threads](https://github.com/request/request/issues/383) about similar topic, but it is not clear from them why should we not specify encoding for (at least) JSON responses.

**Comment by thelinuxlich** [comment]
Maybe send() should accept a charset parameter like the text(), json(), etc methods?

**Comment by floatdrop** [comment]
@thelinuxlich maybe, we already have `media-typer` dependency. Care to send a PR?

**Comment by leo** [comment]
We'll do this for JSON responses only - as spec'd in here: https://github.com/zeit/micro/pull/302
