### ISSUE TITLE
Gracefully close server on SIGTERM

### ISSUE THREAD

**Issue by Siilwyn** [vercel/micro#304]
I always find myself adding the following snippet to close the server when the process receives a request to close:
```js
process.on('SIGTERM', function() {
    server.close(function() {
        process.exit();
    });
});
```

Thoughts on adding this by default? :thought_balloon:

**Comment by maxbeatty** [comment]
Looks like if you're using `bin/micro` this is already done for you https://github.com/zeit/micro/blob/8.0.4/bin/micro.js#L96-L98

**Comment by Siilwyn** [comment]
Thanks for pointing that out however I'm using this module programmatically, wonder why it's in the CLI code though.

**Comment by aks-** [comment]
I am not sure if it's a behaviour which would be okay for library to cause. What if you catch sigterm in your app that uses it and do something else like respawn? Signals are process global. And libraries are not. So I think it belongs in the CLI

Zeit team, thoughts?
