### ISSUE TITLE
Memoize json(req) call ?

### ISSUE THREAD

**Issue by quko8** [vercel/micro#308]
I have some (>4) functions that wraps handler. All of those functions should try to parse json body.

My current solution:
req.json = json(req)

But maybe it will be OK, to memoize json()?

Sorry for my english. I can read, but my grammar is terrible.

**Comment by quko8** [comment]
PR can look like, but i rly didn't know, it will be really fastest?

`const newJsonFn = async req => {
  let state
  return state ? state : (state = await json(req))
}`

**Comment by floatdrop** [comment]
Yep, [it is](https://github.com/zeit/micro/blob/master/lib/index.js#L107-L109) memoized.
