### ISSUE TITLE
Can we recommend error throwing instead of just send?

### ISSUE THREAD

**Issue by quko8** [vercel/micro#312]
Recently i watched libs from https://github.com/amio/awesome-micro and i was a bite confused.

So more libs do something like
```
send(res, 404, 'route not found')
```
instead:
```
throw createError(404, 'route not found')
```

I think throwing errors is better because we can easily write custom error handlers, loggers.
I think `if(res.headersSent)` is terrible.

Libs that not convient (i think)
* micro-jwt-auth
* micro-http-router
* microrouter
(maybe more libs ignore throwing too)

**Comment by timneutkens** [comment]
@quko8 to add to your list microrouter does `send` too, very good point!

**Comment by quko8** [comment]
So, i think we can catch this in micro-dev by code like
```
if(res.headersSent) {
  if(ERROR_CODES.includes(res.statusCode) {
    throw new Error('Use error throwing instead of a just send')
  }
}
```

?

**Comment by timneutkens** [comment]
Will be solved by https://github.com/zeit/micro/issues/369
