### ISSUE TITLE
Support non-Error instances error ?

### ISSUE THREAD

**Issue by nkzawa** [vercel/micro#314]
`throw 'an error happened'`

In this case, micro doesn't print any logs except `undefined`. Should we handle this case, or we can make it clear you always have to throw `Error`.

**Comment by TooTallNate** [comment]
We should throw and make it clear that you have to throw an `Error` IMO. We shouldn't encourage/enable devs to use Strings as Errors.

**Comment by nkzawa** [comment]
Agreed. It would be nice if we can warn it when detecting other types on development.

**Comment by leo** [comment]
👌🏼👌🏼
