### ISSUE TITLE
Handling multipart/formdata requests (Body exceeded 1mb limit)

### ISSUE THREAD

**Issue by mrcageman** [vercel/micro#318]
Just discovered this beautiful library and working on creating an upload microservice with it. Thing is, I can't upload files over 1mb.

I tried using the json/buffer helpers and adjusting the limits accordingly, but the requests fails as soon as it's invoked by micro. It tries parsing the JSON before it even enters the function. Is there a way to adjust the 1mb limit that micro enforces "globally" or at least outside of the function?

**Comment by floatdrop** [comment]
@mrcageman do you start service with `micro-dev`?

**Comment by mrcageman** [comment]
@floatdrop I was just going to respond that I actually pinpointed the issue to, indeed, `micro-dev`. Is there a way though to increase the limit there?

**Comment by sbrichardson** [comment]
I added a pull request to resolve this on micro-dev by allowing to customize the max json file size. 
https://github.com/zeit/micro-dev/pull/53
