### ISSUE TITLE
Replace Node Http server with Mitol

### ISSUE THREAD

**Issue by ansarizafar** [vercel/micro#319]
Consider replacing Node Http server with Mitol server https://github.com/Helidium/Mitol. The performance difference is huge.

**Comment by dima-takoy-zz** [comment]
No please. This is incompatible with 90% ready-to-use npm packages
> https://github.com/Helidium/Mitol/issues/12
> **Implement stream response**
> The response object is a plain object. It should extend ReadableStream

Maybe late.

**Comment by floatdrop** [comment]
@ansarizafar you can use custom HTTP server with micro – see https://github.com/zeit/micro/pull/264 

Also check out [uWebSockets](https://github.com/uNetworking/uWebSockets) – it has more community support.

**Comment by ansarizafar** [comment]
@floatdrop  uWebSockets is amazing but I want to use micro cli. Is it possible to use micro/micro-dev cli with custom server?

**Comment by dima-takoy-zz** [comment]
Just write wrapper. micro-cli is a small js file.

**Comment by leo** [comment]
What @floatdrop said
