### ISSUE TITLE
Return

### ISSUE THREAD

**Issue by rauchg** [vercel/micro#32]
``` js
export default function (req, res) {
  return 'woot';
}
```

and

``` js
export default function () {
  return { a: 'woot' };
}
```

will be equivalent to:

``` js
send(res, 200, 'woot');
send(res, 200, { a: 'woot' });
```

**Comment by rauchg** [comment]
@leo @kevin-roark @tootallnate this is a cool one in case any of you wants to take it

**Comment by kevin-roark** [comment]
on it!

**Comment by kevin-roark** [comment]
I think it should be as simple as https://github.com/zeit/micro-core/pull/3

**Comment by joshbetz** [comment]
Would it make sense to allow passing a response code? Maybe something like

``` js
return [201, 'Created']
```

**Comment by kevin-roark** [comment]
@joshbetz I think at that point it would be almost as simple to just call

``` js
send(res, 201, 'Created')
```

But I'm not totally opposed.

**Comment by luisrudge** [comment]
I think there's great value in only returning a string or raw object. If you want to set the status code manually, use the `send` method. Default for raw string or object should be 200 OK

**Comment by rauchg** [comment]
`[201, 'Created']` is technically a valid JSON response right? so, impossible to disambiguate…

**Comment by wprater** [comment]
we can also return the request directly.

```javascript
var request = require('request');
export default function () {
  return request('http://www.google.com');
}
```

which is nice, but if the request already finished and Im still returning the object its hung.  Is this because the request's `end` method was already called?
