### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by jdbrocca** [vercel/micro#321]

**Comment by leo** [comment]
The ES2015 module syntax is not supported by the latest Node.js version - you'll have to transpile the code before running it with micro.

**Comment by matthecarl** [comment]
@leo while it might be too much to add this as an error hyperlink,  do you think it should be documented in the errors directory?

**Comment by leo** [comment]
If it's not an error link, it can't be part of the directory. If we can make an error link happen, let's try it? Though I'm with you and I think it's overkill - we can't document every scenario not related to micro.

**Comment by matthecarl** [comment]
@leo I agree, documenting each scenario is difficult. A search of [syntaxError: Unexpected token import](https://github.com/search?l=JavaScript&q=SyntaxError%3A+Unexpected+token+import&type=Issues&utf8=✓) results in < 2400 issues so I'll pass on it right now. However, [old-node-version.md](https://github.com/zeit/micro/blob/master/errors/old-node-version.md) documents [transpilation](https://github.com/zeit/micro#transpilation) of async/await and that got me thinking that this could be a _"good first bug"_ for someone new to the project to get up and running. Idea source: opensource.guide [Building Welcoming Communities: _Meet contributors where they’re at_](https://opensource.guide/building-community/#meet-contributors-where-theyre-at). 

If you think it's appropriate, I can open an issue and you could tag it as such? Just let me know if you want the issue filed under micro or micro-dev? 

@jdbrocca this link has a solution for how to transpile your code https://github.com/webpack/webpack/issues/4857
