### ISSUE TITLE
Create a TodoBackend implementation using micro

### ISSUE THREAD

**Issue by moredip** [vercel/micro#325]
Hi,

I'm a curator for [todobackend.com](http://todobackend.com), a community resource showing examples of how to build the same simple HTTP API using different frameworks. We have a good number of node.js implementations contributed already, and we'd love to add an implementation showcasing micro. In fact we have an [issue filed](https://github.com/TodoBackend/todo-backend-site/issues/149) for it!

Creating a todobackend implementation usually only takes a hour or two for someone experienced in the framework they're using. There's lots more information about how to do it on the todobackend site [here](http://todobackend.com/contribute.html).

**Comment by brandon93s** [comment]
The referenced issue (https://github.com/TodoBackend/todo-backend-site/issues/149) has been resolved. I suspect this can be closed.
