### ISSUE TITLE
License Restrictions

### ISSUE THREAD

**Issue by corporatepiyush** [vercel/micro#326]
I am creating a open source NodeJS project with Apache 2.0 license and further want to commercialize it. 
Can i use this library for it, does it clash with license terms of this library ?

**Comment by timneutkens** [comment]
https://github.com/zeit/micro/blob/master/license.md github gives a nice overview of the MIT license 😄

**Comment by corporatepiyush** [comment]
I had a look but did not understand implication of the condition mentioned .. that's why the question
`The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software`

**Comment by iamstarkov** [comment]
@corporatepiyush im not copyright lawyer but i guess it means that when you need make sure to let people know you use this project somehow think of iphone licenses. say like this https://freshdesk.com/third-party-licenses-ios

**Comment by leo** [comment]
Correct. 😊 You're free to use the code in your commercial project, but you need to include the copyright notice from the license in all copies of it.
