### ISSUE TITLE
Visualising requests

### ISSUE THREAD

**Issue by leo** [vercel/micro#33]
As suggested by @rauchg in #15, we should incorporate support for visualizing the requests in terms of the data flow, with built in JSON highlighting and prettifying, among other things.

Here's an example:

![1b624cf2-e120-11e5-977a-d6508f8a19b0](https://cloud.githubusercontent.com/assets/6170607/15124818/0af4b6f4-162a-11e6-9d99-27c660c19f64.png)

**Comment by onbjerg** [comment]
Hmm. What about sensitive information in requests?

**Comment by rauchg** [comment]
@onbjerg this is primarily intended for development, not production

**Comment by onbjerg** [comment]
@rauchg Oh, of course.

**Comment by onbjerg** [comment]
What about headers and non-JSON requests/responses?

**Comment by fdidron** [comment]
Would be great !
How would one optin to that ? Adding a parameter `--debug` running or simply by having `NODE_ENV !== 'production'` ?

**Comment by timneutkens** [comment]
@fdidron see #104. Adds a `--log` flag for that exact behaviour.

**Comment by leo** [comment]
https://github.com/zeit/micro-dev

**Comment by onbjerg** [comment]
@leo You guys keep linking to that, but the repository is still empty ;)

**Comment by leo** [comment]
@onbjerg @timneutkens is on it. It will go online after the next major release (we'll do that today).
