### ISSUE TITLE
UNIX Socket support

### ISSUE THREAD

**Issue by jjwedemyer** [vercel/micro#331]
Hi,
UNIX socket support would add a lot of support and usability to self-hosted users who might want to setup multiple services on one system. It esp. would help naming and keeping services separated in difficult, stuffed environments.
Unfortunately I have no clue how to start on that myself.

regards.

**Comment by rouing** [comment]
I would like this to be a thing.

**Comment by jamo** [comment]
This feature was introduced recently. 
For more details, please check out: https://github.com/zeit/micro/releases/tag/9.2.0
