### ISSUE TITLE
Any recommendation of service discovery and api gateway solution for micro?

### ISSUE THREAD

**Issue by ithinco** [vercel/micro#334]

**Comment by rauchg** [comment]
For development, we currently use: https://github.com/zeit/micro-proxy. It's not currently being used in production, but it could!

In production, we use: https://zeit.co/docs/features/path-aliases.

Hope this helps!

**Comment by paulogdm** [comment]
Hello @rauchg, you dont use `micro-proxy` to do a reverse proxy-like feature?
Right now I have this in mind: req -> `www.mydomain.com` -> `now hosted domain` -> `my micro-proxy service` --> "bounce to a micro service hosted in a subdomain" -> res

**Comment by dotcypress** [comment]
@ithinco for simple service discovery you might try our solution: https://github.com/kitcast/micro-discovery
