### ISSUE TITLE
Why req arg is required in sendError function

### ISSUE THREAD

**Issue by cncolder** [vercel/micro#343]
`type sendError = (req, res, errorObj) => void`

The function not read any values from `req`.

**Comment by paulogdm** [comment]
It "shouldn't". Maybe it can follow the standard args of `send(res, code, ...)`.
Can you make a PR?

**Comment by timneutkens** [comment]
As per this comment I'm going to close this issue: https://github.com/zeit/micro/pull/381#issuecomment-446402957
