### ISSUE TITLE
Test failed for default test

### ISSUE THREAD

**Issue by cloudscape-germany** [vercel/micro#352]
Getting this when running the default test:

```
> xo && ava


  1 failed

  echo back the text
  /Users/tyrion/devel/kube-client-micro/test.js:22

   21:
   22:   t.is(res.body.text, 'Hello!');
   23: });

  Actual:

    undefined

  Expected:

    "Hello!"


npm ERR! Test failed.  See above for more details.
```

**Comment by timneutkens** [comment]
Not sure what you mean 🤔

**Comment by cloudscape-germany** [comment]
when I ran npm test I had to fix a myriad of linting problems (thinking about PRing those), then when the test finally run (hello/:who), I got undefined instead of Hello!Am 18.04.2018 19:03 schrieb Tim Neutkens <notifications@github.com>:Not sure what you mean 🤔

**Comment by timneutkens** [comment]
Note that this is the zeit/micro repository for the `micro` npm package. (Just making sure we're on the same page)

There are no linting errors on this repository and it has 100% test coverage. It also doesn't have a test like `t.is(res.body.text, 'Hello!');`

**Comment by cloudscape-germany** [comment]
Must be from some boilerplate code I pulled in on my side then. Sorry for the confusion! We can delete this thread then. I am currently writing an Kubernetes API Client using Micro https://github.com/nottinhill/kube-client-micro I'm sure I will resolve the problem!

**Comment by cloudscape-germany** [comment]
I know this is closed already, but for the sake of an useful example, could you help me on changing the default example, now really this project's one, to test a real endpoint? I looked around the Web for any working examples, but with no success.

I want to test this endpoint:


```
const dostuff = async (req, res) => {
	const pods = await controller.dostuff.someMethod(req.params.myParam); 
	send(res, 200, dostuff);
};

module.exports = router(
	post('/dostuff/:myParam', dostuff),
);
```

Test Example from Micro: (I want to test if myParam got processed by my dostuff Controller)
```
const micro = require('micro')
const test = require('ava')
const listen = require('test-listen')
const request = require('request-promise')

test('my endpoint', async t => {
  const service = micro(async (req, res) => {
    micro.send(res, 200, {
      test: 'woot'
    })
  })

  const url = await listen(service)
  const body = await request(url)

  t.deepEqual(JSON.parse(body).test, 'woot')
  service.close()
})
```

**Comment by timneutkens** [comment]
`req.params` and `req.body` are both express specific things. Also you're `send`ing a function `send(res, 200, dostuff);` `dostuff` is a function, not an object/string etc.

**Comment by cloudscape-germany** [comment]
Ok for the sake of this example take this endpoint:

```
const hello = rateLimit({window: 5000, limit: 2}, (req, res) => {
	send(res, 200, `Hello, ${req.params.who}`);
});

module.exports = router(
	post('/hello/:who', hello)
);
```

How would you test it?
