### ISSUE TITLE
Dynamic port on Heroku

### ISSUE THREAD

**Issue by starman-vlad** [vercel/micro#357]
Hello,

Not really an issue, but a question.
I've been using your module for quite some time now and it has been working successfully on Heroku with 
```
micro -p $PORT
```

But now I'm seeing logs where it says that: `-p --port is deprecated see --help for information on the --listen flag` 

Heroku uses dynamic ports and this deprecation breaks the app on Heroku and therefore it cannot connect to PostgreSQL Database on Heroku.

Is there anyway that I can use `micro -p $PORT` again in the latest version? Without the environment variable port?

**Comment by starman-vlad** [comment]
Nevermind, it's ok. Works fine with `micro` (without `-l` flag) as of `v9.3.0`.

**Comment by brunolemos** [comment]
I can't make it work on heroku at all, any idea?
`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`.
It works fine when deploying on `now`.

```json
"postinstall": "npm run build",
"serve": "micro dist/index.js",
"start": "npm run serve",
```

```shell
2018-06-30T22:39:12.000000+00:00 app[api]: Build succeeded
2018-06-30T22:39:14.633579+00:00 app[web.1]: 
2018-06-30T22:39:14.633607+00:00 app[web.1]: > app@0.0.1 start /app
2018-06-30T22:39:14.633609+00:00 app[web.1]: > npm run serve
2018-06-30T22:39:14.633610+00:00 app[web.1]: 
2018-06-30T22:39:14.980280+00:00 app[web.1]: 
2018-06-30T22:39:14.980312+00:00 app[web.1]: > micro dist/index.js
2018-06-30T22:39:14.980311+00:00 app[web.1]: > app@0.0.1 serve /app
2018-06-30T22:39:14.980313+00:00 app[web.1]: 
2018-06-30T22:39:15.236756+00:00 app[web.1]: micro: Accepting connections on port 3000
2018-06-30T22:40:13.144946+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

```json
  "dependencies": {
    "@slack/client": "^4.3.1",
    "micro": "^9.3.2",
    "microrouter": "^3.1.3"
  },
  "devDependencies": {
    "@types/jest": "^23.1.3",
    "@types/micro": "^7.3.1",
    "@types/microrouter": "^3.1.0",
    "@types/node": "^10.5.1",
    "concurrently": "^3.6.0",
    "husky": "^0.14.3",
    "jest": "^23.2.0",
    "lint-staged": "^7.2.0",
    "micro-dev": "^3.0.0",
    "nodemon": "^1.17.5",
    "prettier": "^1.13.7",
    "ts-jest": "^22.4.6",
    "ts-node": "^7.0.0",
    "tslint": "^5.10.0",
    "tslint-config-airbnb": "^5.9.2",
    "tslint-config-prettier": "^1.13.0",
    "typescript": "^2.9.2"
  },
```

**Comment by brunolemos** [comment]
Micro is not picking the dynamic port from heroku for me.

If I do `console.log(process.env.PORT)` it prints random ports (e.g. `24074`) but micro seems to always use `3000`: `micro: Accepting connections on port 3000 `.

**Comment by brunolemos** [comment]
Made #367, it fixes the issue.

**Comment by starman-vlad** [comment]
@brunolemos Try adding this to your `start` script
`"start": "micro -l tcp://0.0.0.0:$PORT"`

**Comment by brunolemos** [comment]
@VladimirDev93 thanks this also works
