### ISSUE TITLE
Add an option to not automatically bind to your public IP

### ISSUE THREAD

**Issue by tejashah88** [vercel/micro#359]
While it's nice in some cases to automatically bind to your public IP, I don't feel comfortable having it exposed all the time, even when I'm not using it. A common use case is with Dialogflow, specifically with the "fulfillment" part, which allows me to specify a URL to process incoming requests. Since I often use ngrok to forward those requests to localhost for testing, it would be nice to have a flag to not be listening from the public IP, for security reasons.

**Comment by timneutkens** [comment]
You can use the `--listen` option for this: https://github.com/zeit/micro#command-line
