### ISSUE TITLE
No tests found in index.js

### ISSUE THREAD

**Issue by mrmading** [vercel/micro#363]
I have written my first endpoint with micro and endpoint. I can perfectly run and pass my test using npm run test but when I do commit for some reason that same task throws an exception:

 ✖ No tests found in index.js, make sure to import "ava" at the top of your test file

I have simply an index.js file with my code and then a a test under test/add-key.js

**Comment by maccyber** [comment]
This does not seem like an issue with micro - do your have an example repo?

**Comment by timneutkens** [comment]
Yeah, Micro is not a test runner 🤔
