### ISSUE TITLE
Getting weird console outputs when using micro + micro dev

### ISSUE THREAD

**Issue by dihmeetree** [vercel/micro#366]
Here's an example of what my console looks like. 

**Note**: I am running in development mode with ```micro-dev --watch server.js```

![Error](https://i.imgur.com/b39Eyec.png)

I am using the following technologies:
- zeit micro-dev
- zeit micro
- Next.JS (6.0.4-canary.3)
- zeit hyper console

And I am running on Windows 10 Professional.

Anybody know the reason for this? :)

**Comment by paulogdm** [comment]
Interesting, I believe the issue may be with [micro-dev](https://github.com/zeit/micro-dev). I don't know how Next send content, but this `IF` is being triggered: https://github.com/zeit/micro-dev/blob/master/lib/log.js#L38

Are you sure your `micro-dev` is up-to-date?

**Comment by timneutkens** [comment]
I'm going to close this as the issue is outdated. It's definitely not related to Next.js, it seems like an encoding issue.
