### ISSUE TITLE
Cannot find module 'micro'

### ISSUE THREAD

**Issue by agonbina** [vercel/micro#37]
<img width="403" alt="screen shot 2016-05-22 at 11 39 13 pm" src="https://cloud.githubusercontent.com/assets/3496783/15456634/66fde438-2076-11e6-93d3-98fefb3e7205.png">

I just wasted ~30 minutes because this package is now just exporting `micro-core` and that's what needs to be required for the `npm start` command described in the docs to work.

So instead of 

``` js
import { send } from 'micro';
```

it should be 

``` js
import { send } from 'micro-core';
```

**Comment by rauchg** [comment]
@agonbina I'm very sorry. We recently made this change to improve performance for deployments (where you can now import `micro-core`), and use `micro` for development.

We'll repair the build.

**Comment by onbjerg** [comment]
@rauchg I also just encountered this. Looking forward to a fixed build.

**Comment by nkzawa** [comment]
`3.0.0` has been released.
