### ISSUE TITLE
micro never shuts down when in conjunction with esm

### ISSUE THREAD

**Issue by starman-vlad** [vercel/micro#374]
I'm starting the server with `esm` command and micro is unable to properly shut down.

package.json:
```js
"main": "index.js",
"scripts": {
  "start": "node -r esm ./node_modules/.bin/micro -l tcp://0.0.0.0:$PORT",
}
```

terminal:
```
micro: Gracefully shutting down. Please wait...
```
but it never shuts down. However, if I print something out to the terminal using `console.log()`, it terminates the server successfully.

I have not required the `esm` module in any of my files, since ES6 works well without requiring the module in modules.

System info:
- OS: Linux Mint 19 x64
- Node: 8.12.0
- npm: 6.4.1

**Comment by iamstarkov** [comment]
can you publish minimum reproducible example?

**Comment by starman-vlad** [comment]
![peek 2018-10-26 13-32](https://user-images.githubusercontent.com/12301022/47563979-c5c67300-d923-11e8-8fe0-6ecd03ba8c7f.gif)

If you watch the entire gif, at the end (wait for about ~8 seconds) I have to press Ctrl + C again in order to terminate the local server. But like I mentioned earlier, I am **not requiring** the esm module anywhere in my code since it works as it should just by executing it with the npm command. 

But I have to say that I did not encounter any problems while using the app on Heroku, since it can be properly put into sleep mode.

**Comment by r0mflip** [comment]
@VladimirDev93 as @iamstarkov mentioned can you provide any example that represents what you are running, the file that is run by micro. Most likely `index.js` in your project and/or any other related examples.

**Comment by iamstarkov** [comment]
@VladimirDev93 not the gif, but a the either the whole project or minimal reproducible example. Like the thing I can clone on my machine, install deps, run it and get what you are getting

**Comment by starman-vlad** [comment]
Tried to reproduce the issue but was unable to since micro shuts down on first `Ctrl + C` key combination. I guess that there are no issues with `micro` or `esm` but the problem was on my side. My code was probably doing a heavy work or I had some bugs in my code. As you can see in the gif, it wouldn't shut down on first `Ctrl + C` key combination, but rather on a second try. 

Everything is ok now with the minimal setup that I've tried.

```js
import { ApolloServer, gql } from 'apollo-server-micro';
 
export const typeDefs = gql`
  type Query {
    sayHello: String
  }
`;
 
export const resolvers = {
  Query: {
    sayHello(root, args, context) {
      return 'Hello World!';
    },
  },
};
 
const apolloServer = new ApolloServer({ typeDefs, resolvers });
export default apolloServer.createHandler();
```

```js
{
  "name": "micro-esm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node -r esm ./node_modules/.bin/micro",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-server-micro": "^2.1.0",
    "esm": "^3.0.84",
    "graphql": "^14.0.2",
    "micro": "^9.3.3"
  }
}
```
