### ISSUE TITLE
Hang without error

### ISSUE THREAD

**Issue by crapthings** [vercel/micro#376]
this line will hang without print 1 if there're no data match. why?
const result = db[code] 

```js
const fs = require('fs')
const micro = require('micro')

const db = JSON.parse(fs.readFileSync('./db.json', { encoding: 'utf-8' }))

const server = micro((req, res) => {
  console.log(1)
  const code = req.url.replace('/?code=', '')
  const result = db[code]
  return result
})

server.listen(8910, () => {
  console.log('port 8910')
})
```

**Comment by iamstarkov** [comment]
hello, 

do you have an error and stack trace? also what are the micro's version you use?

can you publish this as a repo with db.json file in place? or perhaps inline `db` so I can test your use case?

**Comment by crapthings** [comment]
node 8.11.3
micro 9.3.3

oh return undefined will cause request hang.
but my first example it doesn't hit console.log(1) weird.
and i even tried try catch block

```js
const obj = {
  a: 1,
  b: 2,
  c: 3,
}

module.exports = (req, res) => {
  const result = obj['d']
  return result // undefined
}
```

**Comment by timneutkens** [comment]
Returning undefined is the same as:


```
module.exports = (req, res) => {
  return
}
```

When nothing is returned we assume you finished the request yourself using `send(` or simply `res.end()`.
