### ISSUE TITLE
Using service.on( 'request' ) to intercept in a test can cause headers to send twice

### ISSUE THREAD

**Issue by roborourke** [vercel/micro#380]
Hi,

I'm following some of the tips from the docs here on testing with AVA but I'm hitting an issue. I have an API endpoint that will trigger a call to another API endpoint in an async manner. In the test I want to be sure that the other endpoint gets hit and returns something appropriate before the main service (`ep1` below) can respond to it.

Example code:

```js
test( 'test api', async t => {
  const service = micro( ep1 );
  const url = await listen( service );

  t.plan(2);

  // Listen for POST to animate.
  service.on( 'request', ( req, res ) => {
    if ( req.url === '/api/ep2' ) {
      t.pass();
      micro.send( res, 200, { ok: true } );
    }
  } );

  const rsp = await fetch( url ); // Request triggers another request to `/api/ep2`

  t.is( rsp.status, 200 );

  service.close();
} );
```

My tests pass ok however I get the following error thrown:

```
Unhandled Rejection: test/ep1.js
  Error: Can't set headers after they are sent.
  send (node_modules/micro/lib/index.js:76:6)
```

Should the `send()` function in micro check for `res.headersSent`? Am I doing something very wrong here?

**Comment by timneutkens** [comment]
The function passed to `micro` has to return something / do something. If you want to change behavior of that function you can enhance it with a higher order function:

```js
test( 'test api', async t => {
  function alwaysPassApiEpTwo(fn) {
    return (req, res) => {
      if ( req.url === '/api/ep2' ) {
        t.pass();
        micro.send( res, 200, { ok: true } );
        return
      }
      
      return fn(req, res)
    }
  }
  const service = micro( alwaysPassApiEpTwo(ep1) );
  const url = await listen( service );

  t.plan(2);

  const rsp = await fetch( url ); // Request triggers another request to `/api/ep2`

  t.is( rsp.status, 200 );

  service.close();
} );
```

**Comment by roborourke** [comment]
@timneutkens that works :) Thanks for taking the time to respond, and so quickly too!
