### ISSUE TITLE
Prototype Poisoning

### ISSUE THREAD

**Issue by sebald** [vercel/micro#388]
Lately there it was discovered that malicious code can be injected via `__proto__` and `JSON.parse`. The following article has more information on the topic: [A Tale of (prototype) Poisoning](https://hueniverse.com/a-tale-of-prototype-poisoning-2610fa170061)

Looking at `mirco`'s source code it seems that using `json` is unsave:

https://github.com/zeit/micro/blob/85d7bd6302345957e13831f1f1f811eb9f69909d/lib/index.js#L116-L122

Should [`Bourne`](https://github.com/hapijs/bourne) be used to fix this in userland or do you plan to update `micro`? 🙂

PS: Would you accept a PR that introduces `Bourne`? I love `micro` for been so simple and small and I am not sure if this would "bloat" it.

**Comment by iamstarkov** [comment]
interesting

**Comment by hor4z** [comment]
Interesting I had not thought about it, I do not think it's something that should be mitigated in the core of Micro, if that were the case you should implement many security methods such as sanitization of parameters in each microservice, it is something that should be prevented in a gateway or a WAF system, reverse proxy etc. Express has the same problem with bodyparser.

**Comment by OlliV** [comment]
I agree with @Hume3. I looked into how we use `micro` internally and the programming patterns we use are already preventing any sort of poisoning from happening. We are always recommending strong `ajv`-style type checking, not allowing extra properties, and sanitizing all input.

**Comment by iamstarkov** [comment]
@timneutkens any comments? is it not an issue? if its not, then why? if it is, then has it been addressed?

**Comment by timneutkens** [comment]
I mean @OlliV posted a comment already and there were no replies for months. So I closed the issue.
