### ISSUE TITLE
Returning strings and throwing errors doesn't respond with a status code

### ISSUE THREAD

**Issue by weedgrease** [vercel/micro#390]
I have the following `index.js` file that I'm deploying using Now:

```
module.exports = async (req, res) => {
  return "Hello world!";
}
```

When I visit the deployed instance, I get a `502`/`NO_STATUS_CODE_FROM_LAMBDA`. I instead used `send(res, 200, 'Hello World')` and things worked fine, though the docs say they are equivalent. What's weird is I get the same error/code when I replace the above return with `throw createError(401, 'Not authenticated')` - my lambda function is still not returning a status code`.

**Comment by timneutkens** [comment]
Are you using `@now/node`? or micro?

**Comment by weedgrease** [comment]
@timneutkens i’m using `@now/node` - didn’t know this param could be any binary :o

**Comment by timneutkens** [comment]
`@now/node` is not micro, we'll be adding an example for micro soon. Until then there's this example: https://github.com/zeit/now-examples/tree/master/nodejs-micro

**Comment by ogorbacheva** [comment]
I have tried this example, but i have the same issue - 502 error. If I use 'send' instead of 'returns', it works correctly.
