### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by nahtnam** [vercel/micro#392]
Hey,

Love the library and idea, but it hasn't been updated in a few months. Just wondering if Zeit has ditched the project or if updates are coming?

Thanks!

**Comment by vinaybedre** [comment]
hey @nahtnam I saw latest commit is 5 days old. Also `micro` is supported out of the box in https://zeit.co/
I doubt, they will kill it in coming days

**Comment by timneutkens** [comment]
Yes it's being maintained and a lot of ZEIT APIs use Micro.

So basically my take on micro is that it's pretty complete.

Besides https://github.com/zeit/micro/issues/369 there is really nothing to add. It works, it's in production, it's being maintained.
