### ISSUE TITLE
Micro doesn't respond in programmatic use

### ISSUE THREAD

**Issue by aredridel** [vercel/micro#403]
I've got a basic server:

```
const http = require('http')
const micro = require('micro')

const server = new http.Server(micro(async (req, res) => {
  return 'Hello world'
}))

server.listen(5000)
```

It doesn't actually respond on port 5000 (request never completes). 

Removing micro from the equation and using this code:

```
const http = require('http')
const micro = require('micro')

const server = new http.Server(async (req, res) => {
  res.end('Hello world')
}))

server.listen(5000)
```
works

This is using node 12.3.1 & micro 9.3.4

**Comment by timneutkens** [comment]
Looks like you're using the programmatic usage for the new version of micro which is currently available as `micro@canary`. For the `latest` branch docs you can visit npm: https://npmjs.com/micro 🙏

**Comment by paulmillr** [comment]
@timneutkens why don't you mention this in README? It's been like 3 months.

**Comment by morgs32** [comment]
🤕 🔫

**Comment by morgs32** [comment]
![image](https://media.giphy.com/media/IQtlYHoWAcxuo/giphy.gif)

How many people have to suffer! (said with jest, but after losing 30 min)

Pull request here: https://github.com/zeit/micro/pull/416
