### ISSUE TITLE
Micro stay alive in background even after closing it

### ISSUE THREAD

**Issue by KASOGIT** [vercel/micro#407]
Hello, every time i close the my server run with nicro it remains alive in the background even if it prompt "gracefully exiting", how can i achieve a complete shutdown of the app ?
I can see in the micro bin code that you're juste caching the process exit event and logging a console.log, is this enough ?
```
function registerShutdown(fn) {
	let run = false;

	const wrapper = () => {
		if (!run) {
                run = true;
                fn(); // registerShutdown(() => console.log('micro: Gracefully shutting down. Please wait...'));
              }
	};

	process.on('SIGINT', wrapper);
	process.on('SIGTERM', wrapper);
	process.on('exit', wrapper);
}
```
<img width="535" alt="Screenshot 2019-07-11 at 08 46 38" src="https://user-images.githubusercontent.com/15908751/61030566-f4a34d00-a3bd-11e9-901e-99ef77f1c06b.png">
<img width="1233" alt="Screenshot 2019-07-11 at 08 51 27" src="https://user-images.githubusercontent.com/15908751/61030567-f53be380-a3bd-11e9-8aaa-a3d7810f6f82.png">

**Comment by devongovett** [comment]
yeah noticed this as well. I think there needs to be a `process.exit()` in there somewhere.

**Comment by carcinocron** [comment]
I'm having the same issue, sudo supervisorctl restart myapp _always_ results in:

```
micro: Error: listen EADDRINUSE: address already in use 0.0.0.0:10180
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at doListen (net.js:1488:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by antoniojps** [comment]
Any updates on this? I seem to be having the same issue. Even after a `service.close()`.
