### ISSUE TITLE
Access to XMLHttpRequest at 'http://localhost:3000/domains/xxx/records' from origin 'null' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by zhaowenyuan** [vercel/micro#415]
Access to XMLHttpRequest at 'http://localhost:3000/domains/xxx/records' from origin 'null' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
I wrote the following code on the server side, but it didn't work!
`		res.setHeader("Access-Control-Allow-Origin", "*");
		res.setHeader("Access-Control-Allow-Headers", "X-Requested-With");
		res.setHeader("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
		res.setHeader("X-Powered-By",' 3.2.1');
		res.setHeader("Content-Type", "application/json;charset=utf-8");`

And the output：
(node:26284) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by jamo** [comment]
Hey, I know the CORS messages and erros can be messy; it seems to be saying that `content-type` is missing from the `Access-Control-Allow-Headers` response:

You'll need to add that header to the CORS allow headers response:
```diff
> res.setHeader("Access-Control-Allow-Headers", "X-Requested-With, content-type");
---
< res.setHeader("Access-Control-Allow-Headers", "X-Requested-With");
```

**Comment by zhaowenyuan** [comment]
[https://github.com/zeit/micro/issues/415#issuecomment-531683591](url)
It worked, thank you!
my code:
```
		res.setHeader("Access-Control-Allow-Origin", "*");
		res.setHeader("Access-Control-Allow-Credentials", "true");
		res.setHeader("Access-Control-Max-Age", "1800");
		res.setHeader("Access-Control-Allow-Headers", "content-type");
		res.setHeader("Access-Control-Allow-Methods","PUT, POST, GET, DELETE, PATCH, OPTIONS");
		// res.setHeader("Content-Type", "application/json;charset=utf-8"); // Opening this comment will cause problems
```

**Comment by AurelianSpodarec** [comment]
Doesn't seem it works for me.

I got this:
Access to XMLHttpRequest at 'http://localhost:8888/wp-json/wc/v3/orders?oauth_consumer_key=ck 02c605438a&oauth_nonce=sSwJtghq&oauth_signature_method=HMAC-SH 56&oauth_timestamp=1601270062&oauth_version=1.0&oauth_signature=H4RmEfiolLCrvq68dF8g71Pxf5cNK1NzQw%3D' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
And this is my code in function.php

```
add_filter('init', 'add_cors_header');
function add_cors_header() {
    header("Access-Control-Allow-Origin: http://localhost:3000");
    header("Access-Control-Allow-Headers", "X-Requested-With, content-type");
}
```

Tried a few things, not sure why this doesn't work?

**Comment by saadazghour** [comment]
@AurelianSpodarec, Same issue here.

**Comment by KiritDiyora** [comment]
I have same issue

**Comment by Merott** [comment]
This [partial port of fastify/fastify-cors to vercel/micro](https://gist.github.com/Merott/8558261f6e16360c67f0b8dbe6bec92c) might help.

**Comment by shail10** [comment]
Can we resolve this from frontend?

**Comment by SandaruwanB** [comment]
use this part to the server
app.options( '*' ,  cors()) or app.options( 'your static URI' , cors())

**Comment by aditimahabole** [comment]
where to write this code...in which file?

**Comment by aditimahabole** [comment]
![image](https://user-images.githubusercontent.com/78752342/223185958-854e5dad-1a35-4700-b766-3735119a37f5.png)

**Comment by aditimahabole** [comment]
how to solve this problem

**Comment by SandaruwanB** [comment]
@aditimahabole first install cors, express packages using "npm i cors express" and create server file and in your server file like below.

const express = require("express");
const cors = require("cors");
const app = express();

app.use(cors());
app.get("/", (req,res)=>{
        res.send("server working");
});

app.listen(8080, ()=>{
        console.log("Server Listen on http://localhost:8080");
});

**Comment by ajaykathwate** [comment]
> ![image](https://user-images.githubusercontent.com/78752342/223185958-854e5dad-1a35-4700-b766-3735119a37f5.png)

Hey,
did you solved this issue?
how?

**Comment by SandaruwanB** [comment]
@ajaykathwate yeah look at the above code. you have to use cors dependency to resolve this problem. then after you can fix it.

**Comment by velkathir** [comment]
![ckeditor](https://user-images.githubusercontent.com/129292316/229759320-08af083b-3477-42aa-8be7-e77587ee65bc.PNG)

This error is display in ckeditor

**Server.js**

const express = require("express");
const path = require("path");
const app = express();
const cors = require("cors");

const port = process.env.PORT || 8000;

app.use(express.static(path.join(__dirname, "build")));

app.use(cors());
app.get("/", (req, res) => {
  res.send("server working");
});

app.get("/", function(req, res) {
  res.sendFile(path.join(__dirname, "build", "index.html"));
});

app.use(function(req, res, next) {
  //console.log(req, res, next, "req, res, nextreq, res, next")
  if (
    req.method === "GET" &&
    req.accepts("html") &&
    !req.is("json") &&
    !req.path.includes(".")
  ) {
    //res.sendFile('index.html', { root })
    res.sendFile(path.join(__dirname, "build", "index.html"));
  } else next();
});

app.listen(port);

**Comment by ENGR-MANSOOR** [comment]
I have same issue after hosting mine react app on ubuntu nginx, without backend, am gettting same issue, i cannot understand why???, any body can guide me?

**Comment by DharanikumarS** [comment]
Access to XMLHttpRequest at 'http://localhost:8080/login' from origin 'http://localhost:8085' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. how to solve this issue in springboot and using jquery

**Comment by xi9d** [comment]
I have been having the same problem until i came accross this article and found to be helpfull
https://www.stackhawk.com/blog/react-cors-guide-what-it-is-and-how-to-enable-it/

**Comment by rahuul296** [comment]
Thanks 

> I have been having the same problem until i came accross this article and found to be helpfull https://www.stackhawk.com/blog/react-cors-guide-what-it-is-and-how-to-enable-it/

Thanks this works for me!

**Comment by vaishnavi1029** [comment]
Access to XMLHttpRequest at 'myurl' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field version is not allowed by Access-Control-Allow-Headers in preflight response. help me how to do it.

const headers = {'Version':'v2'};
                 const fetchdata = await axios.get('/example',{headers});

**Comment by Bharath02062000** [comment]
Access to XMLHttpRequest at 'https://hn.inspectlet.com/ginit/12345678' (redirected from 'http://hn.inspectlet.com/ginit/12345678') from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin.


how to solve this problem?

**Comment by pounyinyiabdeljamil** [comment]
comment résoudre le problème CORS  du cote frontend avec (angular 16)   ? svp aider moi

**Comment by rafaelparolaTechne** [comment]
@Bharath02062000 Please, I'm having the same problem as you. Did you find a solution?

**Comment by karadagmustafa** [comment]
It's a problem you need to solve on the backend. It is necessary to enable cors in securityconfig. 

pay attention to the marked areas  (*).



@Configuration
@EnableWebMvc
public class WebConfig {

    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("http://localhost:3000");  *****************
        config.setAllowedHeaders(Arrays.asList(
                HttpHeaders.AUTHORIZATION,
                HttpHeaders.CONTENT_TYPE,
                HttpHeaders.ACCEPT));
        config.setAllowedMethods(Arrays.asList(
                HttpMethod.GET.name(),
                HttpMethod.POST.name(),
                HttpMethod.PUT.name(),
                HttpMethod.DELETE.name()));
        config.setMaxAge(3600L);
        source.registerCorsConfiguration("/**", config);    ***************
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));

        bean.setOrder(-100);
        return bean;
    }
}

@Configuration
@EnableWebSecurity
public class SecurityConfig {

    private final UserAuthenticationEntryPoint userAuthenticationEntryPoint;
    private final UserAuthenticationProvider userAuthenticationProvider;
    private final CorsConfigurationSource configurationSource;    **********************

    public SecurityConfig(UserAuthenticationEntryPoint userAuthenticationEntryPoint,
			UserAuthenticationProvider userAuthenticationProvider, CorsConfigurationSource configurationSource) {
		this.userAuthenticationEntryPoint = userAuthenticationEntryPoint;
		this.userAuthenticationProvider = userAuthenticationProvider;
		this.configurationSource = configurationSource;
	}

	@Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
        		.cors(c -> c.configurationSource(configurationSource)) *******************
                .exceptionHandling().authenticationEntryPoint(userAuthenticationEntryPoint)
                .and()
                .addFilterBefore(new JwtAuthFilter(userAuthenticationProvider), BasicAuthenticationFilter.class)
                .csrf().disable()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                .authorizeHttpRequests((requests) -> requests
                        .requestMatchers(HttpMethod.POST, "/login", "/register").permitAll()
                        .anyRequest().authenticated())
        ;
        return http.build();
    }
}

**Comment by karadagmustafa** [comment]
This error should be resolved in the backend. The cors error doesn't appear when both the frontend and the backend are at the same url. The most important thing to pay attention to is setting the frontend port
config.addAllowedOrigin (*) 

@Bean
public FilterRegistrationBean corsFilter() {
    UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
    CorsConfiguration config = new CorsConfiguration();
    config.setAllowCredentials(true);
    config.addAllowedOrigin("http://localhost:3000");    *****
    config.setAllowedHeaders(Arrays.asList(
            HttpHeaders.AUTHORIZATION,
            HttpHeaders.CONTENT_TYPE,
            HttpHeaders.ACCEPT));
    config.setAllowedMethods(Arrays.asList(
            HttpMethod.GET.name(),
            HttpMethod.POST.name(),
            HttpMethod.PUT.name(),
            HttpMethod.DELETE.name()));
    config.setMaxAge(3600L);
    source.registerCorsConfiguration("/**", config);
    FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
    bean.setOrder(-100);
    return bean;
}

**Comment by karadagmustafa** [comment]
This error should be resolved in the backend. The cors error doesn't appear when both the frontend and the backend are at the same url. The most important thing to pay attention to is setting the frontend port
config.addAllowedOrigin (*)

@Configuration
@EnableWebMvc
public class CorsConfig {

    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("http://localhost:3000");    ***
        config.setAllowedHeaders(Arrays.asList(
                HttpHeaders.AUTHORIZATION,
                HttpHeaders.CONTENT_TYPE,
                HttpHeaders.ACCEPT));
        config.setAllowedMethods(Arrays.asList(
                HttpMethod.GET.name(),
                HttpMethod.POST.name(),
                HttpMethod.PUT.name(),
                HttpMethod.DELETE.name()));
        config.setMaxAge(3600L);
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(-100);
        return bean;
    }
}

**Comment by karadagmustafa** [comment]
This error should be resolved in the backend. The cors error doesn't appear when both the frontend and the backend are at the same url. The most important thing to pay attention to is setting the frontend port


@Configuration
@EnableWebMvc
public class CorsConfig {

    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("http://localhost:3000");    ***
        config.setAllowedHeaders(Arrays.asList(
                HttpHeaders.AUTHORIZATION,
                HttpHeaders.CONTENT_TYPE,
                HttpHeaders.ACCEPT));
        config.setAllowedMethods(Arrays.asList(
                HttpMethod.GET.name(),
                HttpMethod.POST.name(),
                HttpMethod.PUT.name(),
                HttpMethod.DELETE.name()));
        config.setMaxAge(3600L);
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(-100);
        return bean;
    }
}

**Comment by i-m-fitbeast** [comment]
@karadagmustafa  Thanks... Solution was amazing for back-end developer. It worked for me.

**Comment by prachip1** [comment]
sometimes because of sequence also, this issue appears.  For eg. for me
keeping express.json() first and then route solved this issue.
 app.use(express.json());

app.use('/', require('./routes/authRoutes'))

**Comment by tech7booth** [comment]
![Screenshot 2024-06-05 125034](https://github.com/vercel/micro/assets/170974895/a990fec1-a3e2-41b4-a374-2e88c5c63330)
i am also getting this issue  heres my code

app.use(cors({
    origin: "https://genie-ai0.vercel.app",
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
    allowedHeaders: ['Content-Type', 'Authorization'],
    credentials: true
}));


and i amd using next js as frontend requesting code  -        const { data } = await axios.post(`${BASE_URL}/api/v1${api}`, { email, password }, {withCredentials:true});

**Comment by prachip1** [comment]
okay try doing like this 

app.use((rs,next)=>{
    res.setHeader('Access-Control-Allow-Origin', 'https://genie-ai0.vercel.app');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    next();
});

app.use('/', require('./yourendpointsroutes));

app.use(cors())

try this once

**Comment by tech7booth** [comment]
> Thanks for help but there was another silly issue

**Comment by Victory-Jonathan** [comment]
use cors module on your backend code part.

**Comment by Khaleeq01** [comment]
I deployed MERN stack stack project on vercel backend is working but in frontend this error is coming
![WhatsApp Image 2024-06-06 at 22 38 37_7adf2414](https://github.com/vercel/micro/assets/96943159/9b644b85-d8e5-4964-abba-e2614e07a147)

**Comment by SandaruwanB** [comment]
const allowCors = fn => async (req, res) => {
  res.setHeader('Access-Control-Allow-Credentials', true)
  res.setHeader('Access-Control-Allow-Origin', '*')
  // another common pattern
  // res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT')
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  )
  if (req.method === 'OPTIONS') {
    res.status(200).end()
    return
  }
  return await fn(req, res)
}

const handler = (req, res) => {
  const d = new Date()
  res.end(d.toString())
}

module.exports = allowCors(handler)


You can refer vercel guids to do this. go through this link https://vercel.com/guides/how-to-enable-cors

**Comment by ishaanJ91** [comment]
<img width="395" alt="image" src="https://github.com/user-attachments/assets/a20831be-77e0-4a18-8705-5ce099ed7b36" />

I am having the same error


const cors = require("cors");

// Define allowed origins for CORS
const corsOptions = {
  origin: [
    "https://landstat-frontend.vercel.app", // Vercel production frontend
    "https://landstat-frontend-lmc7nfihm-ishaanj91s-projects.vercel.app", // Vercel preview URL
    "http://localhost:3000", // Local development frontend
  ],
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"], // Allowed HTTP methods
  credentials: true, // Allow credentials (cookies, authorization headers)
  optionsSuccessStatus: 200, // Some legacy browsers choke on 204 responses
};

// Middleware to handle custom headers and CORS
app.use((req, res, next) => {
  const origin = req.headers.origin;
  if (corsOptions.origin.includes(origin)) {
    res.header("Access-Control-Allow-Origin", origin); // Set dynamic origin
  }
  res.header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT,DELETE");
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  );
  res.header("Access-Control-Allow-Credentials", "true"); // Allow cookies
  if (req.method === "OPTIONS") {
    res.status(200).end(); // Handle preflight requests
    return;
  }
  next();
});

// Apply CORS options globally
app.use(cors(corsOptions));

// Example API endpoint (update as necessary)
app.get("/api/example", (req, res) => {
  res.json({ message: "CORS is configured correctly!" });
});

// Preflight request handler
app.options("*", cors(corsOptions));


I dont understand how to fix this on vercel
