### ISSUE TITLE
Please release v 9.3.5 on npm, or revert documentation update

### ISSUE THREAD

**Issue by mikhail-angelov** [vercel/micro#417]
Current npm version is 9.3.4, it's fine, but API is significantly different, compare with v 9.3.5
it's really confusing if user read documentation on GitHub and it does not work with the lates npm version

I'm taking about this PR https://github.com/zeit/micro/commit/df157df15ff0deafde7e10a40b9f0d739365ea35

**Comment by timneutkens** [comment]
As you can read at the start of the readme:
> The below readme is the documentation for the canary (prerelease) branch. To view the documentation for the latest stable Micro version visit npmjs.com/micro.
