### ISSUE TITLE
Client may force buffer decoding to string

### ISSUE THREAD

**Issue by OlliV** [vercel/micro#419]
Src:
```js
const {buffer} = require('micri');

module.exports = async (req, res) => {
    const body = await buffer(req);

    console.log(body);

    return 'txh';
};
```

Input:
```bash
$ curl 127.0.0.1:3000 -d 'ewfewfw'
$ curl 127.0.0.1:3000 -H 'Content-Type: application/json; charset=utf-8' -d 'ewfewfw'
```

Output:
```
<Buffer 65 77 66 65 77 66 77>
ewfewfw
```

This seems to be related to how [raw-body](https://www.npmjs.com/package/raw-body) is used in `buffer()`.

**Comment by James-Quigley** [comment]
Can be fixed by passing a null encoding to `buffer` like so:
```
const {buffer} = require('micro');

module.exports = async (req, res) => {
    const body = await buffer(req, {
        encoding: null
    });

    console.log(body);

    return 'txh';
};
```

**Comment by OlliV** [comment]
Yeah, that's very true but is that how it's supposed to work? The `README` doesn't tell that the function will actually do whatever `iconv-lite` thinks is good per `Content-Type`.

**Comment by leerob** [comment]
Closing as stale - if you're open to contributing, I'd be happy to review a PR!
