### ISSUE TITLE
The version should not be called 9.3.5-canary, it should be at least 9.4-pre, or 10.0-pre

### ISSUE THREAD

**Issue by paulmillr** [vercel/micro#420]
Also, time to release a new version. It's been ages since 9.3.4.

**Comment by kennetpostigo** [comment]
Any chance the next release might be cut soon? Also seems like a pretty important [Pull Request](https://github.com/zeit/micro/pull/418) hasn't gotten brought in.

**Comment by AubreyHewes** [comment]
@paulmillr You should probably describe why the topic/issue has a meaning to you. i.e. describe why not and your issues with it?

The use of `canary` or `pre` is superfluous in semver.
The use of `canary` for code is an old (and also noticeably very new) usage of try and die code.. i.e. bring the canary in.

@kennetpostigo Other issue / Create another issue.

**Comment by paulmillr** [comment]
@AubreyHewes 9.3.5-canary is very different from 9.3.4. Like, "a new release" different. Naming it 9.3.5 feels like it's a simple patch-version bugfix.

**Comment by AubreyHewes** [comment]
@paulmillr You are correct, but the 9.3.5-canary.X version is not npm published... unless you use the github source... so you will never have a problem. It is the code canary version x of the 9.3.5 patch ;-)

I get what you meant, let's not get into a thing about it, sorry if it it sounded like that :+1:  Also waiting for the next release ;-)

**Comment by paulmillr** [comment]
<img width="785" alt="Screen Shot 2020-10-13 at 10 09 55 AM" src="https://user-images.githubusercontent.com/574696/95827332-43b3fc80-0d3c-11eb-882a-25e31e7b1511.png">

**Comment by leerob** [comment]
A new version has been published!
