### ISSUE TITLE
How can I get headers from requests?

### ISSUE THREAD

**Issue by NishidaRyu416** [vercel/micro#422]
I have tried the code below, reading the docs of node.js.

```index.js
module.exports = async (req, res) => {
    const body = await json(req)
    console.log(req.getHeader("something"))
    return body
}
```

**Comment by jamo** [comment]
would this work:
```javascript
req.headers[`something`]
```

https://nodejs.org/api/http.html#http_message_headers

**Comment by NishidaRyu416** [comment]
Thanks for commenting.
I tried it but it did not work properly either.
In detail, the code gives me `undefined`.

**Comment by timneutkens** [comment]
You can log out `req.headers` etc. That would work. It could be that you're not sending the header though.
