### ISSUE TITLE
Cookies not set in response

### ISSUE THREAD

**Issue by nimabrownlee** [vercel/micro#423]
I'm using NextJs getInitialProps trying to refresh the access token. 

```
if(!access_token && ctx.req) {
  try {
    await axios({
      method: 'GET',
      url: 'http://localhost:3000/api/refresh_token',
      withCredentials: true,
      headers: refresh_token ? { cookie: ctx.req.headers.cookie } : {}
    })
  
    console.log(ctx.res.headers)
  } catch (error) {
    console.log(error.response)
  }
}
```

and this is the api endpoint:

```
import axios from 'axios'
import { serialize } from 'cookie'

export default async (req, res) => {
  try {
    const response = await axios.post('http://localhost/oauth/token', {
      grant_type: 'refresh_token',
      refresh_token: req.cookies.refresh_token,
      client_id: process.env.CLIENT_ID,
      client_secret: process.env.CLIENT_SECRET,
      scope: '*',
    })

    const { access_token, refresh_token, expires_in } = response.data
    
    res.setHeader('Set-Cookie', [
      serialize('access_token', access_token, { path: '/', maxAge: expires_in, httpOnly: true, sameSite: true }), 
      serialize('refresh_token', refresh_token, { path: '/', httpOnly: true, sameSite: true })
    ])

    return res.status(200).json({ message: 'yess' })
  } catch (error) {
    res.status(error.status || 500).end(error.response.data.message)
  }
}
```

but when I log the response headers the cookies are not set. Chrome also doesnt show the cookies. Am I missing a step? Maybe because its server side rendering I have to do it another way? Or is this a bug?

**Comment by maxbeatty** [comment]
`ctx.res.headers` won't be updated by your `axios` request to `/api/refresh_token`. You'll need to use what's returned from that request to set your cookies. This example does something similar with [login](https://github.com/zeit/next.js/blob/12241384e73a9d470d4ea2b49c22419be8b4ab3b/examples/with-cookie-auth/pages/login.js#L17-L25) and [set cookie](https://github.com/zeit/next.js/blob/12241384e73a9d470d4ea2b49c22419be8b4ab3b/examples/with-cookie-auth/utils/auth.js#L7).

**Comment by nimabrownlee** [comment]
@maxbeatty Hey. Thank you for your response. Why is that? Has this something to do with how Next.js is built? Because I find it very weird. I can do this in my login endpoint (where I set the cookie in the next-server). Is it because of client side rendering?

**Comment by maxbeatty** [comment]
I don't believe there's any magic to how Next.js handles requests. Have you tried treating `ctx.res` like the `res` in your api endpoint?

```diff
if(!access_token && ctx.req) {
  try {
-   await axios({
+   const response = await axios({
      method: 'GET',
      url: 'http://localhost:3000/api/refresh_token',
      withCredentials: true,
      headers: refresh_token ? { cookie: ctx.req.headers.cookie } : {}
    })
  
+   ctx.res.setHeader("set-cookie", response.getHeaders()['set-cookie'])
    console.log(ctx.res.headers)
  } catch (error) {
    console.log(error.response)
  }
}
```

Another option may be to use redirects to set the proper cookies along the way. Good luck!

**Comment by nimabrownlee** [comment]
@maxbeatty Thanks max. You are truly a beauty. I just added an if statement and it works.

```
 if(ctx && ctx.res && response.headers['set-cookie'])
   ctx.res.setHeader('Set-Cookie', response.headers['set-cookie'])
```
