### ISSUE TITLE
Support host argument

### ISSUE THREAD

**Issue by millette** [vercel/micro#43]
micro-core already supports --host argument. Handy to listen on localhost behind a reverse proxy, for instance. I have some code here: https://github.com/millette/micro/commit/3e814937dec7b2d718210dd6249a8f77648faeae

I could submit a complete PR, but with the above I had to include dist/ in git to make it easier to install.

**Comment by rauchg** [comment]
Makes total sense. Please send the PR and I'll merge it.

**Comment by rauchg** [comment]
Thank you

**Comment by millette** [comment]
Ask and ye shall receive :-)

**Comment by rauchg** [comment]
Thanks @millette
