### ISSUE TITLE
Typings aren't on stable release

### ISSUE THREAD

**Issue by jonahsnider** [vercel/micro#432]
Typings have been written, but aren't being published on npm. Is this intentional? If so, how should TypeScript users be using the typings?

**Comment by jonahsnider** [comment]
Typings are present in latest `v9.3.5` canary release, but not in the latest stable release.

**Comment by adarnon** [comment]
TS types still have not been published. :\

**Comment by jonahsnider** [comment]
micro doesn't seem to be maintained anymore. There's a fork [micri](https://github.com/turist-cloud/micri) that's written in TypeScript I've been using instead.

**Comment by leerob** [comment]
These should be published now: https://github.com/vercel/micro/blob/main/packages/micro/micro.d.ts
