### ISSUE TITLE
How can I get the full request URL? 

### ISSUE THREAD

**Issue by rachelgould** [vercel/micro#433]
I'm using the request URL to receive an access token, and need access to it. However `req.url` only gives me `/api/auth`, whereas the full url is `api/auth#token=23049239857`. Is there a way I can retrieve the URL in its full form?

Thanks!

**Comment by timneutkens** [comment]
Hashes are not sent to the server by browsers:
https://stackoverflow.com/questions/3664257/why-is-the-hash-part-of-the-url-not-available-on-the-server-side

**Comment by rachelgould** [comment]
D'oh! Thanks so much for your help.

**Comment by timneutkens** [comment]
No worries!
