### ISSUE TITLE
How to read file from request?

### ISSUE THREAD

**Issue by ozgreat** [vercel/micro#434]
I wanna read a file from req, how can I do it? I don't wanna use [micro-upload](https://github.com/julianduque/micro-upload)

**Comment by OlliV** [comment]
Just read or also write it to somewhere?
There are various ways to read the body. For small files you could just do:

```
const {buffer} = require('micro');
...
const data = await buffer(req);
```

**Comment by ozgreat** [comment]
> Just read or also write it to somewhere?
> There are various ways to read the body. For small files you could just do:
> 
> ```
> const {buffer} = require('micro');
> ...
> const data = await buffer(req);
> ```

I wanna upload them to s3, but when I try to fs.writeFile(fileName, buf, err => console.log(err)) file is broken

**Comment by rishabhjaishwal** [comment]
Just want to know that anyone contribute to this repo

**Comment by AubreyHewes** [comment]
@ozgreat Micro is designed to be minimal and simplistic. You either need to write your own modules or use community modules.

You mention you do not want to use `micro-upload` ? You do not mention why you do not want to use this. Maybe as you expect a posted binary file?
> _I know that the currently published `micro-upload` is old and fails npm audits. The repo has a dependabot branch that alleviates this, easily defined in package.json._.

For your use case... 

 * Expect an uploaded file (multipart): You would have to write an upload module that would expect a file upload and pipe the data to s3.. maybe you could make a micro-upload-to-s3 module ?
 * Expect posted binary data: then you would have to pipe the data yourself to s3. See also node IncomingMessage documentation.

**Comment by leerob** [comment]
Closing as stale - if you're open to contributing, I'd be happy to review a PR!
