### ISSUE TITLE
Is this framework considered done or abandoned?

### ISSUE THREAD

**Issue by thelinuxlich** [vercel/micro#437]
Because the latest release was a prerelease from almost one year ago.

**Comment by weeezes** [comment]
Hey, if this feels too abandoned for you there's an active fork of Micro called [Micri](https://github.com/turist-cloud/micri), worth checking out :).

**Comment by thelinuxlich** [comment]
Nice!

**Comment by timneutkens** [comment]
Micro has:
- 100% test coverage
- No new changes needed

So it's pretty much done, I experimented with a new programmatic API in the canary releases but haven't gotten around to releasing it.

We use Micro in a lot of the vercel.com API endpoints and it's as stable as it can get.

**Comment by AubreyHewes** [comment]
> Micro has:
> 
> * 100% test coverage
> * No new changes needed
> 
> We use Micro in a lot of the vercel.com API endpoints and it's as stable as it can get.

@timneutkens Maybe this information should be put somewhere for new issues? I was also wondering if I should be utilizing the tech as it has not been updated for a while (also the non reactions on issues).. pondering if zeit (sic) has new tech and abandoned this.
