### ISSUE TITLE
Add a --keep-alive-timeout flag

### ISSUE THREAD

**Issue by elhoyos** [vercel/micro#442]
Say for example, that my load balancer (lb) is configured to keep connections idle up to 60 seconds. I want to be able to do the following and avoid the chances that my lb attempts to connect to a timed out connection:

```sh
micro -l tcp://0.0.0.0:3000 -k 70000
```

This situation has been documented in several places. Here's is [an example](https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/).

Makes sense to create a flag (`--keep-alive-timeout` / `-k`) for this?

**Comment by leerob** [comment]
Closing as stale - if you're open to contributing, I'd be happy to review a PR!
