### ISSUE TITLE
use PORT environment variable as default if set

### ISSUE THREAD

**Issue by eokoneyo** [vercel/micro#444]
Consider the following Docker setup; 

```dockerfile
FROM gcr.io/distroless/nodejs:16
COPY --from=builder /src/app/build /app
COPY --from=builder /src/package.json /app
COPY --from=builder /src/node_modules /app/node_modules
WORKDIR /app
ARG PORT=4000
ENV PORT=$PORT
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
EXPOSE $PORT
CMD ["node_modules/.bin/micro","-l", "tcp://0.0.0.0:$PORT", "index.js"]
```

The port doesn't get set to the value of the $PORT environment variable because CMD will not expand environment variables and the distroless image unfortunately has no shell, so passing the command in something else other than the vector doesn't work. Would it make sense to have micro set port to what ever the $PORT environment if a specific flag is set for cases like this?

**Comment by leerob** [comment]
Closing as stale - if you're open to contributing, I'd be happy to review a PR!
