### ISSUE TITLE
9.4.0 release has a breaking change

### ISSUE THREAD

**Issue by inlife** [vercel/micro#461]
Hey folks,

Unfortunately, one of the changes with the `9.4.0` release broke backward compatibility. I'm referring to this PR from a couple of years ago: https://github.com/vercel/micro/pull/399. It seems like it was sitting in the canary for a while now. Since it was a minor release, any project that used the library with the industry standard dependency reference approach (ex: `"^9.3.3"`) got this new update. 

It seems that sort of a change should have been marked as a major release `10.0.0`. The reason for that is that this change changes the public API for programmatic usage.

I hope you'll find this issue helpful!
Cheers 🎉

**Comment by leerob** [comment]
https://github.com/vercel/micro/pull/460

**Comment by inlife** [comment]
Oh, cool. Thanks!
