### ISSUE TITLE
Version 9.4.1 Breaks @isomorphic-git/cors-proxy

### ISSUE THREAD

**Issue by amxmln** [vercel/micro#462]
Hi everyone,

[@isomorphic-git/cors-proxy](https://github.com/isomorphic-git/cors-proxy) depends on `micro`. One of my projects using that package wasn’t working correctly anymore this morning despite there not being any updates to the package itself.

I narrowed it down to the upgrade of micro from `9.4.0` → `9.4.1` that got applied silently when I upgraded other dependencies via `npm upgrade`.

Forcing `micro` to stay at `9.4.0` via `overrides` in `package.json` resolves the issue.

Steps to reproduce:

1. Init an empty npm-project
2. Run `npm install @isomorphic-git/cors-proxy`
3. Add the following script to the npm "start"-Script: `cors-proxy start`
4. Run `npm start`
5. Go to `localhost:9999` in a browser
6. Observe: the request never completes, the browser keeps loading

Fix:
1. Add `overrides: { "micro": "9.4.0" }` to `package.json`
2. Delete `node_modules` and `package-lock.json`
3. Run `npm install`
4. Run `npm start`
5. Go to `localhost:9999` in a browser
6. Observe: The request now completes and the page loads

This issue did not happen on `v9.3.0`.

I’m posting this here directly because it seems to have been a regression introduced in the patch release to `v9.4.1` which may or may not also affect other packages that depend on `micro`.

Thank you for your time.

**Comment by pmbanugo** [comment]
This will be fixed in the next release. You can stick to 9.4.0 for now.

**Comment by leerob** [comment]
The code has been significantly changed with v10. Please reopen or create a new issue with a reproduction is you are still seeing this issue on v10. Thanks!
