### ISSUE TITLE
v9.4.1 bin/micro.js: const server = new http.Server(serve(module));

### ISSUE THREAD

**Issue by njroye** [vercel/micro#464]
I am not good at English, so I can't accurately describe the problem.

I mark the code in question and note my code.

**The code in question:**
bin/micro.js

```
function startEndpoint(module, endpoint) {
	const server = new http.Server(serve(module));
```

lib/index.js

```
const serve = fn => new http.Server((req, res) => exports.run(req, res, fn));
```

**My code:**
bin/micro.js

```
function startEndpoint(module, endpoint) {
	const server = new http.Server(module);
```

**Comment by pmbanugo** [comment]
I don't clearly know what you mean but I guess you're running into issues with 9.4.1. You should stick to 9.4.0 for now.

@leerob do you plan on doing a new release soon or waiting for the ES module support to be done?

**Comment by njroye** [comment]
Yes, I am running into issues with 9.4.1.

**Comment by Bessonov** [comment]
@leerob please release the 9.5.0 version. The state is very confusing.

**Comment by leerob** [comment]
The code has been significantly changed with v10. Please reopen or create a new issue with a reproduction is you are still seeing this issue on v10. Thanks!
