### ISSUE TITLE
9.4.1 - Wrong type for serve function 

### ISSUE THREAD

**Issue by amilosmanli** [vercel/micro#466]
On TS programmatic usage from the docs does not work correctly, and it's due to the wrong type annotation of `serve` function

https://github.com/vercel/micro/blob/main/packages/micro/types/src/lib/index.d.ts#L5

I think it's return type should be http.Server

**Comment by pmbanugo** [comment]
There's a bug in 9.4.1. Use 9.4.0

**Comment by leerob** [comment]
The code has been significantly changed with v10. Please reopen or create a new issue with a reproduction is you are still seeing this issue on v10. Thanks!
