### ISSUE TITLE
Version 9.4.1 blocks requests on FreeBSD and macOS

### ISSUE THREAD

**Issue by oklas** [vercel/micro#469]
Version 9.4.1 blocks any request. The browser shows "waiting" status.
Version 9.4.0 works fine.

FreeBSD: 12.2 node: v14.16.1.

**Comment by brentvatne** [comment]
experiencing this on macos 12.6, rolling back to 9.4.0 resolved it

**Comment by johnagan** [comment]
> experiencing this on macos 12.6, rolling back to 9.4.0 resolved it

Same for me on Ventura. Could [this](https://github.com/vercel/micro/pull/460/files#diff-a72d83fba7cfc9327cc2c8b0d41aa82972b30a401ffd9119897e59e6e31f007cR26) be the culprit?

**Comment by leerob** [comment]
The code has been significantly changed with v10. Please reopen or create a new issue with a reproduction is you are still seeing this issue on v10. Thanks!

**Comment by oklas** [comment]
This can happen in functions (_like_ `text()`, `json()`, `buffer()`, _etc, in custom code, or in libraries using such functions_) that receive incoming data from an http stream (_from_ ` req :IncomingMessage`) in case data has already been received from it.

This can happen when the user or some library handler gets the control and gets data from the stream, and then some other handler gets the control and tries to get the data from the stream again. In such a case, there will be no more data in the stream because the content length amount of data has already been received. So, it hangs and doesn't respond due to waiting for more data.

Versions prior to 9.4.1 are tolerant of this case.

**Comment by oklas** [comment]
@leerob just to let you notice above
