### ISSUE TITLE
Drop support for Node <6

### ISSUE THREAD

**Issue by rauchg** [vercel/micro#55]
Unless using `-n`. This way we can get rid of the heavy babel deps.

**Comment by millette** [comment]
According to the [official Node LTS schedule](https://github.com/nodejs/LTS#lts_schedule), v4 is still LTS until October, when v6 will take over.

Could this be postponed? Or maybe let micro v4 support node v4, and micro v5 support node v6?

**Comment by leo** [comment]
@millette Exactly! If people want to use an older version of node (not v6), they simply shouldn't update the package to v5...

**Comment by rauchg** [comment]
I'm going to be prioritizing this

**Comment by leo** [comment]
@rauchg 👌

I've also updated [now-serve](https://github.com/zeit/now-serve) and [micro-list](https://github.com/zeit/micro-list) to comply with [this](https://gist.github.com/rauchg/8199de60db48026a6670620a1c33b700).

**Comment by onbjerg** [comment]
Might use [async-to-gen](https://github.com/leebyron/async-to-gen) as well instead of Babel for async/await? https://github.com/zeit/micro/issues/15

**Comment by leo** [comment]
@onbjerg Great idea! But we probably won't be able to drop Babel completely, because the latest node still doesn't support ES2015 module syntax.

**Comment by onbjerg** [comment]
@leo 😓

**Comment by rauchg** [comment]
Done
