### ISSUE TITLE
host option conflicts with help flag

### ISSUE THREAD

**Issue by millette** [vercel/micro#56]
Oups...

```
micro -h localhost index.js # displays help
micro --host localhost index.js # works as expected
```

**Comment by rauchg** [comment]
ugh :\ let's do `-H` ?

**Comment by millette** [comment]
https://www.npmjs.com/package/httpserver uses -H but I've also seen -b (bind). I'll fix it either way, let me know your preference.

**Comment by julianduque** [comment]
`-H` sounds good
