### ISSUE TITLE
file argument is ignored when no-babel option is used

### ISSUE THREAD

**Issue by nkzawa** [vercel/micro#58]
```
micro -n index.js

> Error! Please supply a file.
```

It seems the file argument is mistakenly interpreted as the value of `no-babel` option.

**Comment by julianduque** [comment]
@nkzawa can you test with current `master` if you are still seeing the same error?

**Comment by nkzawa** [comment]
I can't reproduce with current master.

**Comment by julianduque** [comment]
@nkzawa so it works with current `master`? Lets wait until @rauchg publishes a new version to npm \o/, thanks for your report.

**Comment by leo** [comment]
`v5.0.0` was released 6 days ago. @nkzawa does the bug still occur with that release?

**Comment by nkzawa** [comment]
it has already been fixed
