### ISSUE TITLE
-H flag doesn't exist anymore

### ISSUE THREAD

**Issue by onbjerg** [vercel/micro#61]
A lot of things in the README are no longer valid. E.g., the `-H` flag doesn't exist.

**Comment by onbjerg** [comment]
I think it wasn't intentional to remove `-H`. When just typing `micro` it will give this output:

```
☁  deployer [master] ⚡ ./node_modules/.bin/micro

> Error! Please supply a file.

  Usage: micro [options] [command]

  Commands:

    help  Display help

  Options:

    -h, --help          Output usage information
    -h, --host [value]  Host to listen on
    -n, --no-babel      Skip Babel transformation
    -p, --port <n>      Port to listen on
    -v, --version       Output the version number
```

`--host` and `--help` are clashing (both are `-h`).

**Comment by onbjerg** [comment]
I corrected the title accordingly. Some other things in the docs are out of date, too, though.

**Comment by julianduque** [comment]
@onbjerg you are right, a new version needs to be published to npm, ping @rauchg

**Comment by rauchg** [comment]
Done
