### ISSUE TITLE
Release 5.0.1 on npm

### ISSUE THREAD

**Issue by millette** [vercel/micro#82]
According to github, there's a 5.0.1 release but it wasn't published to npm it seems.

I was checking the commit logs, but it's a bit confusing with the renames (micro-core, micro-serve) and all. I'm not even 100% sure there's a difference between 5.0.0 and 5.0.1 - but if there is, an npm release would be appreciated.

**Comment by leo** [comment]
The output of `npm view micro versions` is:

``` js
  ...
  '4.1.0',
  '4.1.1',
  '5.0.0',
  '5.0.1',
  '6.0.1' ]
```

`micro-serve` and `micro-core` have been merged into `micro`. It's now the main package. 😊
