### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by allain** [vercel/micro#88]
On fresh install with:

``` bash
npm init
npm install --save micro
```

and the following in index.js

``` js
const { send } = require('micro');

export default async function (req, res) {
  send(res, 200);
}
```

running `micro -p 3000` yields: 

``` bash
export default function (req, res) {return __async(function*(){
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.require.extensions..js (/home/allain/personal/now/chordie-api/node_modules/async-to-gen/register.js:9:12)
    at Module.load (module.js:473:32)
```

I'm running Node v6.5.0 and micro version installed is 6.0.2

**Comment by allain** [comment]
for some reason it's been dropped as of 6.0.0... README.md should be updated to reflect that.

**Comment by rauchg** [comment]
Yes. Sorry for the confusion @allain. We made a tradeoff in favor of simplicity. With node 6+, the only transform we do is very minimalistic and fast, for `async` and `await`, with a minimal runtime.

**Comment by rauchg** [comment]
btw @allain where did you see the `exports` in the docs? Right now I see `module.exports`

**Comment by allain** [comment]
I'd copied it from the json example.
