### ISSUE TITLE
Compared to Seneca

### ISSUE THREAD

**Issue by khwerhahn** [vercel/micro#9]
How does this project compare to https://github.com/senecajs/seneca? Will it go in the same direction?

**Comment by rauchg** [comment]
`micro` is going to remain lean and opinions free (one of the key points is that it's "just HTTP"). We'll be releasing other modules that play nicely with it. 

Unlike other frameworks, we won't need a `micro-{plugin-name}` family of modules that only work for this particular stack. As long as modules return a `Promise`, they can be `await`ed. The only other important contract is that we discourage extending `Request` and `Response`. Modules should expect these as parameters.

**Comment by luisrudge** [comment]
@rauchg awesome response :)
