### ISSUE TITLE
Consider remove `async-to-gen` after Node.js 7.0 released?

### ISSUE THREAD

**Issue by amio** [vercel/micro#98]
And bump requirement to Node.js 7.0 😏

This would solve #89 and #90 too I think.

**Comment by albinekb** [comment]
Node 7.0 won't include native async/await without flags? 💭 
https://github.com/nodejs/node/pull/8503#issuecomment-249389530

> Async functions seem to be on track to ship with V8 5.5. Since Node.js v7.x is going to ship with V8 5.4, async/await won't be officially supported. Experimental support will be available behind the harmony flags.

**Comment by amio** [comment]
Oops, my mistake >.<

Still have to wait until Node.js officially support async/await, without the `--harmony` flag.

**Comment by amio** [comment]
While, what about a `micro@next`? I think I'm so eager to get rid of `async-to-gen` :P
